### ISSUE TITLE
3bot allows identifiers to start with numbers

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#120]
forces us to do https://github.com/threefoldtech/js-sdk/pull/407

- [ ] Migrate existing users that start with numbers
- [ ] Add validation to no longer allow 3bot name to start with a number during registration

**Comment by zaibon** [comment]
The phonebook in the explorer also doesn't prevent a user to be created with a number as first letter. Do you also want it to be changed there ?

**Comment by MathiasDeWeerdt** [comment]
I dont see a problem with names start with a number? 

But we could enforce this for new users, existing should be able to keep their names ofc.

**Comment by ken-de-moor** [comment]
Will be part of gridDB, closing old dead issue
