### ISSUE TITLE
Should show somewhere that notification may not be received if the app wasn't open 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#125]
Should show somewhere that notification may not be received if the app wasn't open (or use more permissions if needed for the app). You need to open the app then click on send notification

watcher: @despiegk

**Comment by MathiasDeWeerdt** [comment]
We could add this message when you enter your username in the browser.
The reason we don't permanently allow notifications when the app is closed is due to battery drain and this would need firebase to be implemented.

**Comment by xmonader** [comment]
Let's go with the low hanging fruit then please and have that message in the browser window

**Comment by xmonader** [comment]
Why was this closed?  It's still the same in the browser (no indication you need the app open)  and still requires the app to be open 
![image](https://user-images.githubusercontent.com/64129/93688087-81b65b80-fac3-11ea-8e35-a2c027bf35e2.png)

**Comment by ken-de-moor** [comment]
Followup here https://github.com/threefoldtech/threefold_connect/issues/231
