### ISSUE TITLE
Oneplus 6t does not get login notification

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#140]
See https://www.gsmarena.com/oneplus_6t-9350.php

This phone is android 9, upgraded to android 10, so it is definitely one of our supported OS

Two users with the same phone have the exact same issue,

Recovering the account on another device does trigger the login flow correctly.

**Comment by MathiasDeWeerdt** [comment]
@coeneivan Has the oneplus 6, which is basicly a hardware copy of the oneplus 6T. Custom roms are even developed for both phones simultaniously, which indicates a shared code and driver base. 
https://www.gsmarena.com/compare.php3?idPhone1=9350&idPhone2=9109

I would need a screenshot of the settings app to know exactly which version and kernel build they are running. 

Do the people who tested the app run the stock software provided by oneplus or have they unlocked their bootloader and rooted their phones or even flashed another rom and or custom kernel? 

Have they enabled developer options and disabled / enabled certain agressive power/battery saving features? 

Which version of the app was tested? (Latest production 2.0.0?)

**Comment by ken-de-moor** [comment]
Can't fix without debugging on the phone since we can't reproduce on any other phone even one model off this version, or emulated. It happens on one of our devices.
