### ISSUE TITLE
It's possible to skip agreeing to the terms and conditions.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#169]
1) On the final step before agreeing, just press the back button on your device

=> You are now immediately taken to signup without ever agreeing to the terms and conditions.

**Comment by JonasWijne** [comment]
![image](https://user-images.githubusercontent.com/6184820/101069580-7dfe8500-359a-11eb-9813-16c334e26e8d.png)
this was in the figma, should i change it?

**Comment by ken-de-moor** [comment]
Managed to still skip it, I was able to press "get started" without actually ticking the I agree box. Which got me to the signup.
