### ISSUE TITLE
Pressing Enter doesn't send notifications to the mobile in TF connect login

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/threefold_connect#178]
- Pressing Enter doesn't send notifications to the mobile
- There were login button it doesn't show up
- Browser firefox

![Screenshot from 2020-12-20 11-43-02](https://user-images.githubusercontent.com/10658229/102710433-f2cfff80-42ba-11eb-82b8-93e030a5735e.png)

**Comment by OmarElawady** [comment]
i have the same this issue on ubuntu firefox

**Comment by ken-de-moor** [comment]
We've never been able to reproduce on any device and therefor not been able to fix either. I've seen previous screenshots where people get gateway timeouts. Are we sure it is not some local setup that is just networking wrong?
