### ISSUE TITLE
signedAttempt data doesn't return lowercase data

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#179]
https://github.com/threefoldtech/3Bot_connect/pull/118 thought this was merged (all as lowercase)  but apparently, it's not. or maybe in some other PR, 

https://github.com/threefoldtech/3Bot_connect/blob/development/backend/__main__.py#L163 the data in signedAttempt still as is and that's giving problems with users like 
![image](https://user-images.githubusercontent.com/64129/102715598-350b3800-42df-11eb-94c3-96f5dbb092b7.png)

**Comment by xmonader** [comment]
related to https://github.com/threefoldtech/js-sdk/issues/1877#issuecomment-748591290

**Comment by ken-de-moor** [comment]
This was fixed by lowercasing all new data, the name and email fields are stored on the user's phone and we can't just update this in the database.
