### ISSUE TITLE
what is the final app name?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#183]
thought it was Threefold connect then it became TF Connect now in the screen it shows
![image](https://user-images.githubusercontent.com/64129/103436818-762d1180-4c28-11eb-98e8-dc0bbbc504b6.png)

**Comment by sasha-astiadi** [comment]
ThreeFold Connect and TF Connect is basically the same.
TF Connect is short version of it. depends on where you use it, preferably use long version.
short version is used when the long version is too long for the required character counts.

**Comment by xmonader** [comment]
Consistent name is needed, I need to instruct the user to open a specific app and they can't just type the wrong name.

**Comment by sasha-astiadi** [comment]
@ken-de-moor  is there character limitation from android / apple ? if not, threefold connect it is.

**Comment by ken-de-moor** [comment]
Translated to bug at https://github.com/threefoldtech/threefold_connect/issues/199

Name will be ThreeFold Connect
