### ISSUE TITLE
Integrate TF Connect in TFGrid Database

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#187]
See important discussion in older tickets:

https://github.com/threefoldtech/home/issues/859

https://github.com/threefoldtech/home/issues/884

And tfgrid db ticket here : https://github.com/threefoldtech/home/issues/1083

All data should be unified in one database
- [ ] Get all TF Connect data in TFGrid database
- [ ] Get all OpenKYC data in TFGrid database
- [ ] Change ThreeFold Connect to connect to this database

**Comment by weynandkuijpers** [comment]
This issue has not been update for a long time.  Please reconsider if this is part if this release or the next.  I'll remove it if not update and considered part of this release.  Bump it up to in progress is this needs to be done in this release or push it to the next one.

**Comment by despiegk** [comment]
we prob need to take other approach to do with cosmos, lets postpone now
