### ISSUE TITLE
[STAGING] Add phone number does not default to my country.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#191]
Should default to Belgium, currently Defaults to USA for me.

**Comment by JonasWijne** [comment]
It should use locale, it could be that you use usa as your locale

**Comment by ken-de-moor** [comment]
@JonasWijne locale is English ( Belgium ), changing this also seems to have no impact I keep getting USA, which is also country code 1 so I think it's just defaulting to 1 maybe?
