### ISSUE TITLE
[STAGING] Add phone number popup layout does not match rest of the app.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#192]
Example of other screens :

![image](https://user-images.githubusercontent.com/59569757/104932427-e87f4f00-59a7-11eb-8734-f7f065745feb.png)

Add phone number screen: 

![image](https://user-images.githubusercontent.com/59569757/104932480-f6cd6b00-59a7-11eb-89c0-13c8f4ab497f.png)

**Comment by JonasWijne** [comment]
this is due to technical reasons StateFull Widget vs Stateless widget, will check how to fix or recreate a simalar widget for statefull dialog widgets

**Comment by JonasWijne** [comment]
should be fixed in revision
