### ISSUE TITLE
App name is different from android to ios

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/threefold_connect#199]
Currently on  Android :

App store and application name : ThreeFold Connect

Name when saved on phone : ThreeFold Connect

----------------------------

Currently on Apple :

App store and application name : ThreeFold Connect

Name when saved on phone : ThreeFoldConnect

----------------------------

Please change ThreeFoldConnect to ThreeFold Connect

**Comment by ken-de-moor** [comment]
Edited your original comment with specific instructions for the devs. The name was set on multiple levels so made it clearer what they need to fix.

**Comment by xmonader** [comment]
@ken-de-moor  This issue been open for 18 days, will we be able to have that in 2.5 release or we need to push that to 2.6?

**Comment by weynandkuijpers** [comment]
Why should we push this forward - changing ThreeFoldConnect to ThreeFold Connect sounds easy....

**Comment by ken-de-moor** [comment]
App releases are not tied to grid releases. And can't be as we don't control release cycles/versions in app store.

**Comment by ken-de-moor** [comment]
Can't be validated on staging, different configs. Will be validated on prod release.
