### ISSUE TITLE
Change staging to be exactly the same name and logo from production.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#200]
3 releases in a row now that the logo and/or name was wrong. Can't validate it on staging because other logo's and names are being used.

We need staging to be an exact copy of production wherever possible otherwise it's impossible to validate. No changes configs for logo/name or other things that can go wrong during deployment once it's too late to validate.

**Comment by jdelrue** [comment]
Logos adjusted to new logo (TF logo instead of 3bot). However configs are separate for each env, we need to triple check before release.

**Comment by ken-de-moor** [comment]
Ok, I will personally punish anyone who messes up the deploy in the future.
