### ISSUE TITLE
[Iphone] entering the pin twice wrong, makes the right one don't work

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#204]
### Steps
1- Open the app
2- Go to settings 
3- Show phrase 
4- Type the pin wrong, then press ok (should be done twice)
5 - Try to enter the right pin, then press ok

### Expected
When the wrong pin is typed, it should show a message that the pin is wrong.
When the right pin is typed, it should unlock and can see the phrase.

### Result
https://user-images.githubusercontent.com/41957921/106447703-7b30eb00-648a-11eb-8586-3e687c67c2e7.mp4

**Comment by ken-de-moor** [comment]
Used to work, seems to suddenly be broken indeed.

Need to investigate what exactly is blocking this functionality from working properly.

**Comment by ken-de-moor** [comment]
@xmonader I validated the fix on staging, no clue about commit. We're doing an all around bugfix release on staging right now once everything is validated we'll push to production. I can provide the staging APK if you want.

**Comment by xmonader** [comment]
I see, no worries thank you @ken-de-moor , would be great if that info is added when closing issues too :)

**Comment by jdelrue** [comment]
.
   .:;:.
 .:;;;;;:.                 The info is right there 
   ;;;;;
   ;;;;;
   ;;;;;
   ;;;;;
   ;:;;;

**Comment by ken-de-moor** [comment]
Re-opened due to not working on IOS
