### ISSUE TITLE
Opening ThreeFold Connect app with slow/no internet connection results in black screen

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/threefold_connect#206]
- To re-produce: 
disable wifi/3g
open the app

Should get something like no connection and please try again maybe something like:

<img src="https://user-images.githubusercontent.com/10658229/106457373-92c2a080-6497-11eb-8b04-9a182d3c545d.png" width="320">

**getting blank page**

<img src="https://user-images.githubusercontent.com/10658229/106457227-555e1300-6497-11eb-8c77-194bd7e8bc30.png" width="320">

**Comment by ken-de-moor** [comment]
duplicate https://github.com/threefoldtech/threefold_connect/issues/198
