### ISSUE TITLE
TFConnect: Allow tft fee of less than 0.1  if the tx funding service requires less

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/threefold_connect#207]
We want to change the transaction fee to 0.01 but to allow this gracefully it would be best if the wallet does not check for 0.1 tft fee but for 0.1 tft to be the maximum fee

**Comment by jdelrue** [comment]
@tobiaschielens will check today. Follow up by EOB

**Comment by tobiaschielens** [comment]
Fixed in https://github.com/JimberSoftware/stellar-crypto/commit/bf67ed01ea19b10edd98c120716572ffeeae5151
The check transaction function has been changed.
Will need to display the correct fee as mentioned here: https://github.com/threefoldtech/threefold_wallet/issues/79
When @robvanmieghem pushed his changes to staging @ken-de-moor will be able to test

**Comment by weynandkuijpers** [comment]
Issue is being worked on - so put it in progress.  Please keep the issue updated.

**Comment by ken-de-moor** [comment]
@robvanmieghem changes almost ready on our end. Could we deploy the dynamic transaction fees on testnet so we can immediately move forward once they're live within a couple hours?

Also how can I send transactions to my wallet with <0.1 Fee? The transaction sent from the app are still 0.1 Fee so I don't have a way to simulate/test lower fee values.

**Comment by robvanmieghem** [comment]
@ken-de-moor  This has been deployed on testnet

**Comment by sasha-astiadi** [comment]
@robvanmieghem is it ready for verification?

**Comment by ken-de-moor** [comment]
@sasha-astiadi live on staging and I'm verifying. There were 2 issues so far but both were in Jimber side of things and have been fixed now.

Just need to validate one UX problem before we can put it live.

Currently it says in the app that the fee will be 0.1 TFT, and in reality for example it can actually be less than 0.1 TFT, it might only be 0.01 TFT that is deducted from the user their account.

It would be best to have this dynamic and have an API where we can GET the actual exact fee to display to the user, but for now we can put this live, with the only UX problem being that users sometimes pay less fee than they thought they'd have to pay.

I recommend we go live with this and the UX thing can become a seperate issue.

**Comment by ken-de-moor** [comment]
Will follow up the UX issue in https://github.com/threefoldtech/threefold_wallet/issues/188

The change in this ticket can go live.

**Comment by ken-de-moor** [comment]
Will change "Fee" to "Max Fee" and then deploy live.
