### ISSUE TITLE
Paying with app redirects with wrong wallet selected

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/threefold_connect#222]
## Description
When clicking on the transfer button in the selected wallet in the application, the direction to the screen with the details of the transfer contains the wrong wallet selected and need to be adjusted manually. 
This could lead to people paying from the wrong wallet without noticing. 

### Iphone:
**Screen 1** : (Vdcmain wallet)
![image](https://user-images.githubusercontent.com/17128393/113294175-f41bba00-92f6-11eb-8d8d-798eb618fd0d.png)
**Screen 2** : (Daily wallet selected)
![image](https://user-images.githubusercontent.com/17128393/113294222-0138a900-92f7-11eb-88d4-92fc34cf8546.png)

### Android:

https://user-images.githubusercontent.com/17128393/113294405-3b09af80-92f7-11eb-911c-d8fd24dc69e9.mp4

**Comment by ken-de-moor** [comment]
@ranatrk 

Fix should be live, can you validate?

**Comment by ranatrk** [comment]
@ken-de-moor yes works fine now. Thank you
