### ISSUE TITLE
Create yggdrasil iOS implementation

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/threefold_connect#223]
Current Android implementation:

- Users clicks connect button; startvpn() method is called. The keys of the user are sent in this request, which makes the user always have the same ip . In Yggdrasil, STATIC_IP should be set for this to work. In the default Yggdrasil implementation, the keys are generated but in the Flutter one we need, the keys are specific to the user and will be sent from Flutter.
- Best peers are found from list https://jimber.io/peers.html 
(BestPeers.kt). We use 75ms as a metric, 3 peers of <75ms stops the pinging loop.
- The Yggdrasil connection is made in Kotlin (YggdrasilTunService.kt)
- ReportIp event is triggered which calls the flutter callback; this updates UI with the correct IP address
- The user gets connected status and can click disconnect to disconnect from Yggdrasil network

Repos:
- Original yggdrasil ios repo
https://github.com/yggdrasil-network/yggdrasil-ios
- Yggdrasil github
https://yggdrasil-network.github.io/
- Our flutter plugin
https://github.com/threefoldtech/yggdrasil_flutter
- Information about ios installation
https://yggdrasil-network.github.io/installation-ios-app.ht

Specialities:
- Yggdrasil is built in Golang, in android you can build a aar file to access this go code using specific build parameters in Yggdrasil-go (export ANDROID=1). Same exists in the build file for ios (export IOS=1). We had some trouble building but steps will probably be different for ios.

**Comment by robertvanhaecke** [comment]
a

**Comment by ken-de-moor** [comment]
Had to be disabled again. Delayed to next release.

**Comment by ken-de-moor** [comment]
@LennertDefauw1 please complete ticket with current state

**Comment by LennertDefauw1** [comment]
Currently, Yggdrasil in iOS is still disabled due a small issue. Currently debugging, found what could cause the problem and now working on a (hopefully) working fix.
