### ISSUE TITLE
when leaving the app, Yggdrasil connection is lost

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#225]
- open app
- connect to the planetary network
- leave app 
- open app
- no connection to the planetary network

**Comment by ken-de-moor** [comment]
This is as designed, it is not possible to have open VPN connections without the app at least being backgrounded. When it is fully closed, the connection will close. Which is what I would expect as a user from security and privacy standpoint.

It does keep the connection when the app is backgrounded however.
