### ISSUE TITLE
Impossible to load wallet page after stellar account has been destroyed

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/threefold_connect#229]
I have an issue when I try to load the wallet page. 
I think the problem started after I deleted a stellar account that was linked to my app.

I tried to logout and do a recovery, but it did not fix the problem.

Is there anything else I can try ?

**Comment by ken-de-moor** [comment]
@zaibon fix should be live, sorry for the delay. 

If a single destroyed wallet is now in the list, it'll only fail to load that one. And you can still go to details to remove it if you want.

**Comment by zaibon** [comment]
Nice, Thx. Is this going to be available in a next update? Or should it already be available now? I'm running 2.6.1 -116

**Comment by ken-de-moor** [comment]
> Nice, Thx. Is this going to be available in a next update? Or should it already be available now? I'm running 2.6.1 -116

@zaibon it was hotfixed so should be immediately available when you load your wallet.

**Comment by zaibon** [comment]
Then there is still something going wrong. Here is the error message I get: ![Screenshot_20210522-131448.jpg](https://user-images.githubusercontent.com/303164/119224660-c2a5ba80-baff-11eb-8513-eb0a3fea60e9.jpg)

**Comment by ken-de-moor** [comment]
@zaibon seems you aren't getting lucky, this isn't even the original error anymore but an update that happened in stellar that introduced a bug on their end. This has now also been resolved. Please let me know if it works now.

**Comment by zaibon** [comment]
I'm still seeing the same error. Is there any action to be taken in my side? Like disconnect and re import my seed?

**Comment by ken-de-moor** [comment]
@zaibon I'll contact you on telegram so we can do some exact debugging, guessing at the error doesn't seem to be working very well right now.
