### ISSUE TITLE
Support page has invalid links

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/threefold_connect#230]
- Pressing mail button gives the following
![image](https://user-images.githubusercontent.com/10658229/114299159-2200bb80-9aba-11eb-8074-f2eff32c9d5d.png)
![image](https://user-images.githubusercontent.com/10658229/114299164-29c06000-9aba-11eb-8106-208239a63aec.png)

- Pressing add attachment button crashes the app
![image](https://user-images.githubusercontent.com/10658229/114299185-48bef200-9aba-11eb-8909-79f038f31106.png)

**Comment by ken-de-moor** [comment]
@waleedhammam what app and phone version is this? I simply don't have that button available at all. Not sure what triggers the scenario where you would see it.

**Comment by waleedhammam** [comment]
@ken-de-moor app version 2.6.1
Phone is Samsung note 9 and iPhone 8

**Comment by ken-de-moor** [comment]
Repro steps :

First actually send a message to support, only then does the mail button appear.


Throws an error unknown URL scheme on a mailto: field

**Comment by MathiasDeWeerdt** [comment]
We will hide the button through injecting some css.
