### ISSUE TITLE
Show notifications in case of attempt login to authenticate

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/threefold_connect#234]
It would be great to show a notification to alert about current login process to select the emoji/authenticate instead of searching for the app and opening it
- Maybe users can have authorized devices to avoid spam

**Comment by ken-de-moor** [comment]
Was a feature that was shelved on purpose due to the huge battery drain an implementation like that would need. Similar apps like itsme used locally by millions also don't do it for this same reason. I understand the functional question though but it's giving technical issues.
