### ISSUE TITLE
ThreeFold Connect not receiving login attempts for some users.

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#235]
EDIT from ken, more tickets with same issue :

https://github.com/threefoldtech/threefold_connect/issues/258

From the testers chat user Enigma

![image](https://user-images.githubusercontent.com/64129/116818686-f890f800-ab6c-11eb-8989-4d67da5ca1ab.png)

## Context
**Enigma:**
> Hi. I'm stuck on the authenticate part. Is something supposed to pop up in my threefold connect app? App is set up with id and tft in wallet. Am I supposed to logout in the app somehow first?

**xmonader:**
> Enigma you need to hve the app open otherwise it won't work

**Enigma:** 
> Yeah app is open. Nothing pops up. I've tried going to settings, wallet, and home...but can't see anything to authenticate. 
Also just to confirm...when browser page asks for my ID, it is just the first part I type in not the entire ID with the .3bot?

**Comment by xmonader** [comment]
this issue happened with me today, it worked after closing the app 7 times.

**Comment by ken-de-moor** [comment]
@xmonader 

Just checked logs and can't find any errors. Can't reproduce it myself either.

Could you maybe give some more feedback or repo exactly on which part it goes wrong? 

I never get the issue myself so it's very annoying to debug.

Currently checking with @MathiasDeWeerdt if we can find anything in the code.

**Comment by MathiasDeWeerdt** [comment]
There seems to be a ping/pong timeout of 3 seconds which closes the websocket connection. (Default socketIO implementation)

Resetting the connection and forcing a reconnect could be a viable solution in combination with increasing this timeout. To about 10 seconds(+-).

**Comment by MathiasDeWeerdt** [comment]
Closed until further notice. 

Sending another attempt always seems to work if the first one didn't arrive for some reason. 
If anyone has this problem consistently please re-open the ticket and PM me personally so that we can find a solution together.
