### ISSUE TITLE
 There is a problem to get approve on 3bot login, from app threefold connect.

### ISSUE THREAD

**Issue by masteritua** [threefoldtech/threefold_connect#246]
There is a problem to get approve on 3bot login, from app threefold connect.
When I am not click button, but only type ENTER after name 3bot - approve is not get to app.
![Screenshot_2021-04-06 ThreeFold Connect](https://user-images.githubusercontent.com/33724112/113657137-f3dc3f80-96a5-11eb-8180-cf473a8a57f5.png)

**Comment by nbabenko** [comment]
having same error in my phone Samsung Galaxy 9, before it was working. It does not depend on the network (tried with different connection types), works from another phone nearby with the same account

**Comment by ken-de-moor** [comment]
Buttons is only disabled if the account doesn't exist yet. Validated with several accounts and browsers.

Other ticket is there for logins not arriving.
