### ISSUE TITLE
Node Heartbeat Checking in App

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/threefold_connect#254]
A lot of farmers are relying on the explorers for this right now, problem is that is it's "pull" they need to check it every single day if their node is online. 

A setting where one could provide their farm ID and this would make it possible to email them updates on their node(s) status(es) would be very beneficial to all I think.

**Comment by ken-de-moor** [comment]
@VonSub App is for all functionalities to use any ThreeFold product ( With TFT as payment, 3bot login as login service ). Grid specific things don't really belong in the app. Plus we'd need to have the app opened 24/7 to even be able to do the health check, as the app isn't doing anything when it's closed.

Proposal is to make a website that does the same thing instead, maybe unify it inside an existing site where it belongs?

**Comment by VonSub** [comment]
Agreed. Will see if we can make a different setting elsewhere for this.
