### ISSUE TITLE
No 2FA on app when trying to login to VDC

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#258]
Trying to log in to VDC, but not receiving a notification to do 2FA in the app. Nothing pops up when opening the app either.

- benjelloun.3bot
- GBLBH6ZMOAYBN6CAMJ3MKJWELIEQGO6754HN4SOSSGWUS4ICXAKKWCLB

Multiple people are reporting this issue.

**Comment by ken-de-moor** [comment]
duplicate https://github.com/threefoldtech/threefold_connect/issues/235
