### ISSUE TITLE
Move threefold connect backend to tfgrid

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/threefold_connect#261]
The current idea on how to move the threefold connect backend to the tfgrid wil consist of the follow actions: 

1) Users will need to enter their phone number and confirm this through an SMS. This is mandatory and not optional. We should enforce an end-date.
2) Once the phone number has been verified the account from the user will be **merged into the tfgrid**. 

The funding will need to happen through some sort of funding service.

**How will the merge happen?**

- Initial migration of all the accounts could happen through some sort of root function on the tfgrid, so our backend can be shutdown and run inside the tfgrid. We can provide a json dump of all the users with their publickey / doublename / email to be imported.
- The backend code gets adjusted according to what we need to implement and talk to the blockchain.

**How will the registration work for new users?**

- They will be prompted to verify their phone number through an SMS, once this is completed the funding service can fund the user to write his data to the blockchain and he will be registered in the application. 

**How will the current flow work with OpenKYC?** (Used for email and SMS verification)
- This service doesn't really save anything it simply signs objects and returns them to the user for safe-keeping. The only thing saved in this service is during the registration flow. The important part of this application is the seed which is used to sign the objects and should be kept safe.
- This still needs to be discussed on how to proceed.

**Comment by MathiasDeWeerdt** [comment]
Meeting with @DylanVerstraete at the moment discussing this migration. 

1) First off init this: 
https://github.com/threefoldtech/tfgrid-api-client

2) Then use the funding service with that address
3) Then create the entitity. (+- 6 seconds)

https://github.com/threefoldtech/tfgrid-substrate

**Comment by MathiasDeWeerdt** [comment]
1) We are currently blocked due to the fact that the API has to communicate to substrate is made in javascript and our app uses dart. There are different solutions to this to 'transpile' JS to dart but these only seem to work in basic and simple scenarios. The tfgrid-api-client has too many dependencies and the javascript Runtime used by these transpilers / interpreters can't handle it. 

2) Another option would be to do this call in the backend but this would require us to send the user their private key to a server and leave the device.

3) A third theoretical option would be to create a front-end only web application load this application into a web-view on the device and let everything execute on the client-side. Now the web-view in android is limited and this would have to be heavily tested to make sure the migration can be done smoothly. This would also hinder the user and need to open a web-view during registration and recovery of an account.

Looking for other possibilities and I am now trying to exhaust all possible javascriptRuntimes which can run in dart, but so far its not executing complex code.

**Comment by jdelrue** [comment]
A intermediate REST API will be made that uses the JS SDK. The signing will happen on the device but a simplified version of the JS SDK API will be exposed to the app. @MathiasDeWeerdt will take initiative to create this.

**Comment by DylanVerstraete** [comment]
A small Rust client can be written and be compiled to wasm. You can then use this wasm binary in your flutter app.

https://medium.com/flutter-community/flutter-web-and-wasm-49217497b0ed

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/home/issues/1105

**Comment by sasha-astiadi** [comment]
https://github.com/threefoldtech/home/issues/1105 is this helm chart issue related to this issue? @jdelrue

**Comment by despiegk** [comment]
need other specs, will prob be on cosmos

**Comment by ken-de-moor** [comment]
Closed since this is too outdated, new ticket should be made if new specs are there.
