### ISSUE TITLE
Adding attachments to the support function in app not working

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#266]
User could not add screenshots in the support function in the app, worked on the website. - see screenshots below. 
![e92da646e2b46eed8766436d4d036c5b595e1426](https://user-images.githubusercontent.com/31733464/125453913-d570a78a-9ff1-4d22-9e10-c8cebc10bc2c.png)
![a0f0d9903a02f07d2025c98737d1ff33b9bae138](https://user-images.githubusercontent.com/31733464/125453935-0acab0d8-db10-42b0-a394-ea55fea294a0.png)

**Comment by sabrinasadik** [comment]
Three more users with the same issue - P. Kraft, Ajh6909 and R. Bansal

**Comment by FlorinaRogers** [comment]
> 
> 
> Three more users with the same issue - P. Kraft, Ajh6909 and R. Bansal

and one more user now Thai Ma

User Thai reports that gif and smiley icons work but the + icon and the email icon do not work on the app. User even tried installing the app on another phone but had the same complaint. In the user's own words: Right now i am using the app. everytime i am sending picture i have to use my notebook with the email adress(see screenshot) wich is connected with our chat in this app. a little complicated but its the only way i can send you my screenshot.

Please see the image below:

![image](https://user-images.githubusercontent.com/86709961/127662828-4156ebc9-5423-45c3-9cf1-82b4f677f0d7.png)

**Comment by FlorinaRogers** [comment]
@jdelrue 

Please give an update on this issue.

**Comment by jdelrue** [comment]
We can add this to the TODO list of TF connect, maybe take it in with the next release but a quick fix is not possible due to large overhead of building / releasing new apps.

Added to backlog here: https://github.com/threefoldtech/threefold_connect/issues/273

We will close issue if implemented

**Comment by sabrinasadik** [comment]
@FlorinaRogers pls tell the users that we will fix this in the next release of the app, but for now only workaround is through web

**Comment by FlorinaRogers** [comment]
@sabrinasadik 

I have let the users know on chat.

**Comment by jdelrue** [comment]
Fixed in #273
