### ISSUE TITLE
2.7 ui improvements review

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/threefold_connect#270]
Figma link https://www.figma.com/file/2vzr85oukUjXpW6kD4t3W8/tfconnect2.8?node-id=0%3A1

**checklist**

**home**

- [x] less gap between icon and title
- [x] smaller logo n image, move it up, perfectly  centered
- [x] add intro text, centered: 
Welcome to 
**ThreeFold Connect App**!
Click on the **menu** icon
to get started

- [x] careful with spacing, make it as similar as it looks on figma

**menu**

- [x] smaller logo
- [x] slightly move icon to the right not too close to the edge of the screen
- [x] Digital T
- [x] less gap between icon n text

**digital twin reservation**

- [x] on description text, privacy not frivacy
- [x] Reserve Digital Twin for Life for Your Loved Ones (title use smaller letter size, and first letter capital except for words like 'for' 'and' 'in'... etc)
- [x] on description text, loved ones written in small letters
- [x]  Reserve Now  (button first letter capital)
- [x] Buy Product Key (button first letter capital)
- [x] add text link at the end of the description for both dialogue: Visit [Digital Twin website](mydigitaltwin.io) for more info.

**all generic / blog**

- [x] follow hierarchy, the back bar shouldnt be bigger than the main menu bar. 

- [x] spacing, alignment horizontal vertica; all should be the same amount, in line with the upper one

- [x]  blog title text should be smaller

**transfer**

- [ ] where is the back button on transfer

**wallet**

- [ ] where is vesting

**reserved DT**

- [x] change title
- [x] , Change text, add link to website. 
- [x] less gap between description and telegram
- [x] change button text

**success page**

- [ ] add icon
- [ ] add title description
- [ ] add text and link to reserve digital twin page

**reservation info page**

- [x] change title
- [x] First Letter Capital

**Comment by sasha-astiadi** [comment]
@jdelrue @JonasWijne @LennertDefauw1 just put some more checklist above based on updated figma yesterday

**Comment by sasha-astiadi** [comment]
![photo_2021-07-30_16-54-47](https://user-images.githubusercontent.com/43240801/127671750-7fee9cd0-ea36-4e92-8d92-7ea13aa91f5b.jpg)

![photo_2021-07-30_17-03-38](https://user-images.githubusercontent.com/43240801/127672854-0073dda7-3f18-4bcf-968a-36748373149c.jpg)

**Comment by MathiasDeWeerdt** [comment]
The wallet will be updated on a later date: https://github.com/threefoldtech/threefold_wallet/issues/255

**Comment by sasha-astiadi** [comment]
- [ ] remove the entire reservation part for now. everything else looks good @ken-de-moor
