### ISSUE TITLE
Fix add attachment on support tab

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/threefold_connect#273]
Attachment on support is not working as described here https://github.com/threefoldtech/threefold_connect/issues/266

please close support issue if implemented

**Comment by MathiasDeWeerdt** [comment]
I can't seem to reproduce, can  u test @ken-de-moor ?

**Comment by ken-de-moor** [comment]
Original issue linked has errors for the mail button, not add attachment button. Add attachment also works in production.
