### ISSUE TITLE
Implementation of DS-DNS for the Digital Twin

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/threefold_connect#277]
We are going to add a mandatory scope in the login flow from the Digital Twin to the app and with this scope we are going to implement an endpoint to link the derived public key (dpk) from the Digital Twin to the threefold connect user.

When we trust the dpk from the Digital Twin we can simply add 2 endpoints.
- PUT /users/jdelrue
{ "yggdrasilAddress" : 123:123:123, "appid" : "jdelrue.digitaltwin-test.jimbertesting.be" }

For this endpoint, the request will contain a signed object with the user his yggdrasil ip and appId. The backend will verify the dpk to the user and when this succeeds it will write the yggdrasil ip and appId to the database.

- GET /users/jdelrue/
A public endpoint for anyone to access, it will return the user data, including IP based on the user his name. 

- GET /search/users/<partialname>
Get all users that match partialname

**Comment by MathiasDeWeerdt** [comment]
Currently implementing the endpoint APIs to verify the signs and save the data in our database.
Also creating the correct migrations for our production environment.

**Comment by MathiasDeWeerdt** [comment]
**Example request of updating your yggdrasil IP address in our backend**
  PUT /api/users/digitaltwin/singlecore2.3bot HTTP/1.1
  Host: 127.0.0.1:5000
  Content-Type: application/json
  Content-Length: 219
  
  {
      "app_id": "http://192.168.1.2:8081/",
      "signed_yggdrasil_ip_address": "0gWs0EeSD3p7FJk5jdNi3wlWA4QFDKGanifjA2ryKw86Qb9PyjV+p2ZLSu+OJ+H1AerBggV7DEyB2e1/4FngDTIwMDE6ZGI4OjMzMzM6NDQ0NDo1NTU1OjY2NjY6Nzc3Nzo4ODg4"
  }

The `signed_yggdrasil_ip_address` is the IP address signed with the private key used in the digital twin. As long as the sign, name and app_id are valid then ip will always be updated.

**Comment by JonasWijne** [comment]
desired response for list of digitaltwin locations :
```json
[
{"id":"testboy","location":"200:dd36:924c:dc59:4a80:b26b:cbb8:43b4"}
]
```

**Comment by JonasWijne** [comment]
desired response for list of digitaltwin locations :
```json
[
{"id":"testboy","location":"200:dd36:924c:dc59:4a80:b26b:cbb8:43b4"}
]
```

**Comment by MathiasDeWeerdt** [comment]
Done.
