### ISSUE TITLE
STAGING - Verfication mail is not received.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#278]
Unverified in settings, tried resending invite 2 times. Nothing was ever received.

Using email kendemoor92@gmail.com and 3bot name kentyy.3bot

V 3.0.0 - 130

**Comment by MathiasDeWeerdt** [comment]
Verified, going to fix.

**Comment by MathiasDeWeerdt** [comment]
Something / someone stopped the openkyc container, starting it back up fixed it. Might have been an accident on the staging server.
