### ISSUE TITLE
STAGING - Verification SMS for phone number was not received.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#279]
Added phone number and also tried a resend 2 minutes later.

No SMS was ever received, using a +32 belgian nr

**Comment by MathiasDeWeerdt** [comment]
Was a problem with our SMS service provider. Seems to be fixed now.

**Comment by MathiasDeWeerdt** [comment]
Edited some of the texting logic, should be fine now. Fixed on staging and production.
