### ISSUE TITLE
STAGING - Biometrics doesn't work when you only have face recognition.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#280]
Used to be that I could either use face recognition or fingerprint.

On my phone I have face recognition unlock but no fingerprint.

Under settings I can enable fingerprint to log in, but it doesn't do anything as my phone doesn't have fingerprint.

Used to be that it'd dynamically detect what your phone does or doesn't have, and provide that option.

**Comment by MathiasDeWeerdt** [comment]
Flutter regression error due new and old plugins requiring difference flutter dependencies. (aka: dependency hell)
Updated everything as far as I could without breaking other features. 

Fixed.
