### ISSUE TITLE
None of the planetary network services seem to work.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#286]
Tried 5 different ones on the official list, nothing connects.

Tried with both staging and production apps, says connected, opens VPN, but can't actually connect to IPV6 resources on the phone.

https://yggdrasil-network.github.io/services.html

For example http://[21e:e795:8e82:a9e2:ff48:952d:55f2:f0bb]/

**Comment by jdelrue** [comment]
Are disabled for now; yggdrasil updated and we are not compatible
