### ISSUE TITLE
Remove the concept of .3bot from the app.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#296]
Any and all mensions of 3bot name should be gone.

Replaced by "username"

3bot name => username
doublename => username

things like kendemoor.3bot should just be kendemoor

Don't forget frontend, login sites, emails from openkyc,...

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The concept of 3bot has been removed

![3bot](https://github.com/user-attachments/assets/cf8b6c57-6be0-48f1-827b-86b12527f86c)
