### ISSUE TITLE
Deprecate old IOS and Android versions for stability and security. 

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/threefold_connect#309]
IOS: 
- Only support IOS 14 or higher. (More then 85% of all IOS devices use IOS 14: https://developer.apple.com/support/app-store/)

Android: 
- Only support Android 8.1 or higher. (Well over 80% of all devices support android 8.1 or higher according to multiple sources.)

**Comment by jdelrue** [comment]
Will be further discussed in #324
