### ISSUE TITLE
Disabled deposit 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#311]
### Summary

Cannot proceed to the deposit screen

### Environments
- Android OS v11
- iOS v14.7

### Version
- App: 3.1.0-132
- Wallet: 2.8.2-HF01

### Steps to reproduce
1. Open the app.
2. Navigate to _Wallet_ screen.
3. Go to a wallet
4. After you activate BTC, hit deposit

### Current behavior
Redirected to "disabled deposit" screen

### Expected behavior
Should be redirected to the "actual deposit" screen

### Relevant screenshots

**Comment by ken-de-moor** [comment]
As designed, deposits have been disabled until a new solution is found.

https://github.com/threefoldtech/threefold_wallet/issues/259
