### ISSUE TITLE
Vesting pool link is broken 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#312]
### Summary

The more information link for TFT vesting redirects to a non-existing page.

### Environments

- Android OS v11

- iOS v14.7

### Version

- App: 3.1.0-132

- Wallet: 2.8.2-HF01

### Steps to reproduce

1\. Open the app.

2\. Navigate to _Wallet_ screen.

3\. On the wallet's details screen select the 4th icon (screenshot 1).

4\. A warning popup will show up, click on the information link about vesting (screenshot 2).

### Current behavior

The vesting pool link redirects to a non-existing page (screenshot 3).

### Expected behavior

The vesting pool link must redirect to a working page.
Link: https://library.threefold.me/info/threefold#/tokens/threefold__vesting_pool

**Comment by ken-de-moor** [comment]
I'll leave it open so it can be invalidated after the linked issue is resolved.

**Comment by jdelrue** [comment]
Wallet issue
