### ISSUE TITLE
ThreeFold BTC Asset Guide - dead link 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#313]
### Summary

Activate BTC Asset pop-up has a dead link

### Environments
- Android OS v11
- iOS v14.7

### Version
- App: 3.1.0-132
- Wallet: 2.8.2-HF01

### Steps to reproduce
1. Open the app.
2. Navigate to _Wallet_ screen.
3. Go to a wallet
4. Then click on activate
5. In the pop-up, click on "ThreeFold's BTC Asset Guide" link

### Current behavior
Popup notification has a dead link and returns 404 -- not found.

### Expected behavior
Popup should have a valid link and should redirect to the respective document.

**Comment by ken-de-moor** [comment]
I'll leave it open so it can be invalidated after the linked issue is resolved.

**Comment by jdelrue** [comment]
BTC is disabled
