### ISSUE TITLE
Assets persistent loading animation

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#315]
### Summary

Wallet's transfer screen shows a loading animation that is not hidden once the assets list has been loaded.

### Environments

*   Android OS v11
*   iOS v14.7

### Version

*   App: 3.1.0-132
*   Wallet: 2.8.2-HF01

### Steps to reproduce

1.  Open the app.
2.  Navigate to the _Wallet_ screen.
3.  Go to a wallet.
4.  Then navigate to the transfer tab.

### Current behavior

At the bottom of the assets list, a loading animation is always visible (screenshot).

**Note:** if you switch tabs the animation disappears

### Expected behavior

The loading animation must be hidden once the assets have loaded.

**Comment by jdelrue** [comment]
Wallet issue
