### ISSUE TITLE
Unlimited email verifications 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#316]
### Summary

A user is allowed to request unlimited email verification while his/her is being unverified

### Environments
- Android OS v11
- iOS v14.7

### Version
- App: 3.1.0-132
- Wallet: 2.8.2-HF01

### Steps to reproduce
1. Create an account
2. Navigate to settings
3. Hit Verify email icon  more than once

### Current behavior
Unlimited email verification can be sent

### Expected behavior
Should restrict the user in sending unlimited verifications and then resulting in abusing SMTP server.

**Comment by ken-de-moor** [comment]
The email sent is like 2kb in size, there are so many API calls in any kind of application that can be much more abused than this. Really a non-issue from any functional perspective. If someone wants to constantly spam call that barely takes any resources then they always can.
