### ISSUE TITLE
Consent pop-up on entering vesting 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#317]
### Summary

A consent pop-up appears every time vesting is being visited.

### Environments
- Android OS v11
- iOS v14.7

### Version
- App: 3.1.0-132
- Wallet: 2.8.2-HF01

### Steps to reproduce
1. Open the app.
2. Navigate to _Wallet_ screen.
3. Go to a wallet
4. Then navigate to Vesting tab
5. Hit agree on the pop-up
6. Navigate any other tab and then go back to vesting

### Current behavior
The pop-up re-appear asking again for consent.

### Expected behavior
It should remember the user's choice and appear only once.

### Attached screenshots
![image](/uploads/e21a915a9a1e4a2934b542bf6f5cb300/image.png)

**Comment by ken-de-moor** [comment]
By design due to legal reasons.
