### ISSUE TITLE
Threefold connect: Oops something went wrong...

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#324]
Oops something went wrong...

![image](https://user-images.githubusercontent.com/64129/138054648-b9c8627e-0cc5-4b65-abcb-4f8d6d38fdd4.png)

over Wifi, mobile data. with multiple people atm.

**Comment by jdelrue** [comment]
We will try to fix with a flag

**Comment by abom** [comment]
Is this already fixed? if someone forgot to save his phrase somewhere, then his account is just "lost", even if he bought a new phone, he wouldn't be able to access his older account to recover it in his new phone!

**Comment by jdelrue** [comment]
Should be fixed
