### ISSUE TITLE
some QR codes are not detected on Android phones while it works on IPhone

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/threefold_connect#349]
it happened with me `sometimes` the QR is not detected from Android phone while it works on IPhone
tried the following QR with three different Android phones and it didn't work
![Screenshot from 2021-11-15 15-50-34](https://user-images.githubusercontent.com/1689456/141795507-99705e92-13d6-4bdf-975a-0afedd604bd8.png)

**Comment by ken-de-moor** [comment]
Issue seems to be related to the QR code used, my normal phone scanner can't pick it up either.

We'll need to look into how to generate a QR code with less data in it, or higher quality. As lower end camera's appear to fail to scan it, unrelated to TF Connect technology.
