### ISSUE TITLE
Inconsistent response of Wallet Address Data if I have more than wallet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/threefold_connect#350]
I've 2 wallets in my tf connect app, first time i chose the first wallet

- After decryption of the results walletAddress is None. 

![image](https://user-images.githubusercontent.com/10658229/142454847-f36826e7-a055-49d8-80e6-6c63f8efc0a3.png)

- Scope is defined as here

![image](https://user-images.githubusercontent.com/10658229/142455144-67225b29-08b1-483f-9e58-4f838841a7cf.png)

3bot name: waleedhammam.3bot
wallet address: `GCNHLX2ZTX2HDXCIQATZRSIHK2ECKEMKZCMSMIWBOTS2DZYUJBMHNXJA`

- Selecting another wallet makes it work!

![image](https://user-images.githubusercontent.com/10658229/142455642-b0dc9373-d9e5-4da0-944e-26baf1350806.png)

- Trying again with previous wallet it works

![image](https://user-images.githubusercontent.com/10658229/142455965-bb1ccdd6-5afb-4c8d-b3e7-0e952f5105b6.png)

**Comment by jdelrue** [comment]
@LennertDefauw1 please check

**Comment by LennertDefauw1** [comment]
@waleedhammam  is fixed, will release this ASAP. If you want, I can already send you thee .apk. Just let me know :)

**Comment by waleedhammam** [comment]
> @waleedhammam is fixed, will release this ASAP. If you want, I can already send you the .apk. Just let me know :)

Thanks!

**Comment by ken-de-moor** [comment]
@waleedhammam it seems the update has just gone live on the play store. Iphone will follow later.
