### ISSUE TITLE
TF Connect app is crashing after launch

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/threefold_connect#354]
OS: Android 11.0.2.0
Model: xiaomi 5+
Contact: https://t.me/eavatar108
Friend of Nickolay. 

https://user-images.githubusercontent.com/4426772/143091317-59e744c0-51b9-4a3b-a986-d87eaa6e3b3c.mp4

The Russian-language crash report window in saying "The app experienced an error...... / Send report / Cancel"

**Comment by LennertDefauw1** [comment]
Contacted Nickolay on Telegram.

**Comment by LennertDefauw1** [comment]
![image](https://user-images.githubusercontent.com/43674202/148766415-caec2483-0799-4208-b4ae-1b2f507a0598.png)

**Comment by LennertDefauw1** [comment]
![Uploading image.png…]()

**Comment by LennertDefauw1** [comment]
![Uploading image.png…]()

**Comment by LennertDefauw1** [comment]
![Uploading image.png…]()

**Comment by LennertDefauw1** [comment]
![image](https://user-images.githubusercontent.com/43674202/148770804-a11d19e0-211b-48ba-8078-6516f8761992.png)

**Comment by LennertDefauw1** [comment]
![image](https://user-images.githubusercontent.com/43674202/148770866-a80c41d2-081f-4396-8596-c6af6afefa6d.png)

**Comment by LennertDefauw1** [comment]
The user has read the message and didn't reply anymore. So I assume this issue has been fixed.
