### ISSUE TITLE
Threefold connect: after verifying identity, the first login attempt doesn't pop up since there is a widget unmounted

### ISSUE THREAD

**Issue by LennertDefauw1** [threefoldtech/threefold_connect#355]

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The first Login after verifying identity worked normally.

https://github.com/user-attachments/assets/4554c544-1f5e-4604-8644-9cb2840b6e10

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407477#case_4412672
