### ISSUE TITLE
3Bot name should be valid identifier 

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/threefold_connect#361]
users can create 3Bot names which is not valid identifiers and can cause many troubles like `tex.gEvolution.3bot`

- here we can see the 3Bot name has a capital letter and a `.` which will cause many errors

**Comment by LennertDefauw1** [comment]
On it

**Comment by LennertDefauw1** [comment]
Can't reproduce, all special characters gets automatically stripped in the sign up process.

Can't even find the 3bot name of tex ?

https://login.threefold.me/api/users/tex.gEvolution.3bot

**Comment by ken-de-moor** [comment]
It's impossible to create a name like this in the platform, this has been disabled for about 2 years. Only legacy accounts could still possibly have this.

I looked up the user and his actual 3bot name is gevolution.3bot
