### ISSUE TITLE
Connectivity timeout is too quick for slow connections

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/threefold_connect#363]
App users with slow internet connections may see the "No internet connection available" message when in fact their connection simply requires more time to load the page.

Potential solutions:

1. Simply disable the timeout
2. Add a warning to the loading page after the timeout duration that internet may not be available
3. Make the timeout or the timeout duration a setting

**Comment by scottyeager** [comment]
@ken-de-moor, can you comment here?

**Comment by LennertDefauw1** [comment]
Currently busy updating the app to null safe, in this release, I will make the timeout message configurable via feature flag.

**Comment by scottyeager** [comment]
Thanks @LennertDefauw1

**Comment by ken-de-moor** [comment]
Validated on staging, going live on next version.
