### ISSUE TITLE
Delete email column in database

### ISSUE THREAD

**Issue by LennertDefauw1** [threefoldtech/threefold_connect#367]

**Comment by LennertDefauw1** [comment]
Since migration to pkid, it is not necessary anymore to store email in database

**Comment by jdelrue** [comment]
Create backup first, share with @sabrinasadik

**Comment by sabrinasadik** [comment]
is that done?

**Comment by ken-de-moor** [comment]
@LennertDefauw1 what is the state on this? Is this something that's already done? Is it something we'll check in 3.6?

**Comment by LennertDefauw1** [comment]
Not done yet, can break many features, will look for this in next release
