### ISSUE TITLE
Qr-code scan is not working

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/threefold_connect#370]
![image](https://user-images.githubusercontent.com/26298009/148747148-cf06153e-c7fd-4d5c-9ffc-5856b59fd9d7.png)

**Comment by ken-de-moor** [comment]
Duplicate of https://github.com/threefoldtech/threefold_connect/issues/360

Also not a TF connect issue.

If the phone camera can't read it, there is nothing TF connect can do to change that.
