### ISSUE TITLE
App gives blanc screen

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#375]
![telegram-cloud-photo-size-4-5994443962372438538-y](https://user-images.githubusercontent.com/31733464/149914816-a963c522-679e-4f46-85c0-1d6495caff99.jpg)

Tried restarting the app, does not work.

**Comment by LennertDefauw1** [comment]
Does the user have the latest app version?

**Comment by sabrinasadik** [comment]
Ash has version 3.4.3, not working for him either.

**Comment by LennertDefauw1** [comment]
Weird since nothing got changed in the last weeks (backend / app). Maybe something broke cause of the migration yesterday?

Both on IOS?

**Comment by ken-de-moor** [comment]
Was resolved, wizard issue.
