### ISSUE TITLE
Test login on forum using Safari/Brave/Chrome

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/threefold_connect#377]
![image](https://user-images.githubusercontent.com/1687505/150342309-60edede0-408a-494f-8e24-ed45260e8f9f.png)

- Check if all login flows work
- If email is unverified the forum should show a proper error, create ticket in forum repo if not
-

**Comment by ken-de-moor** [comment]
Specific chromium version is breaking the login flow somehow.

The newest version released on 21 jan fixes this. Chromium is used on Edge, Brave, Chrome, and some others. So the issue can be on several browsers.

97.0.4692.99 is the chromium version where it's fixed
