### ISSUE TITLE
New SMS flow UAE and specs for future

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/threefold_connect#378]
We should stop using twilio and use a real SMS gateway to send SMS, since too many problems with sending SMS's over Twilio. (UAE doesnt work etc)

**Comment by JonasWijne** [comment]
more info about UAE sms's for twilio: 
https://www.twilio.com/guidelines/ae/sms

**Comment by despiegk** [comment]
see #389

**Comment by LennertDefauw1** [comment]
Closing this issue since there is no phone verification anymore used inside the app.
