### ISSUE TITLE
Strange wording on manual

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#397]
Change 'PLEASE DO NOT FORGET TO REMEMBER YOUR MNEMONIC WORDS, YOU WILL NEED THEM IN NEXT STEPS.'
to
'PLEASE REMEMBER TO WRITE DOWN YOUR MNEMONIC WORDS. YOU WILL NEED THEM IN THE NEXT STEPS.'

**Comment by ken-de-moor** [comment]
@sabrinasadik I assume this is an older ticket belonging to farmers and not the app? And probably already resolved there? I'll close for now, please re-open with a bit more context if my assumption was wrong.
