### ISSUE TITLE
Unable to upload file to support chat on Android

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/threefold_connect#406]
User reports that using the plus sign button to upload a file to a support chat within their Connect app on Android does not work. Instead, the app is closed.

Device: Samsung Galaxy A41
TF Connect Version: 3.4.6 – 144

**Comment by ken-de-moor** [comment]
Can't reproduce on same version and almost same phone ( galaxy a50 ). What file format is this?

**Comment by ken-de-moor** [comment]
![image](https://user-images.githubusercontent.com/59569757/157065840-8139c7e9-32b3-44ba-a1fe-843425c3fac6.png)

**Comment by ken-de-moor** [comment]
Closed due to being an isolated case that we can't reproduce and don't have repro steps for.
