### ISSUE TITLE
User receives 2 SMS's on verification

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/threefold_connect#414]

**Comment by ken-de-moor** [comment]
Just tried and had it first try myself.

1) Fully new account.
2) Email is verified, phone number is unknown.
3) Press verify button, fill in phone number and press yes on the prompts to immediately verify.

=> 2 SMS received

![image](https://user-images.githubusercontent.com/59569757/158546701-1be2c588-2577-4b75-8ad6-c2d7f15a9279.png)

**Comment by ken-de-moor** [comment]
If you fill in your phone, or if your phone number ris already known and you press verify => 1 SMS.

If your phone is unknown, new user, and fill it in for first time, then say "YES" on the I want to verify now. Then it sends 2 SMS

**Comment by ken-de-moor** [comment]
This is however also a production issue so if it's not an easy fix, I wouldn't delay the release for it.
