### ISSUE TITLE
can't login with my 3bot id but other ids works fine

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/threefold_connect#416]
can't use my 3bot id to login and checked the identity page and the account was verified.
I receive the notification on the app but when I choose the emoji i got an `Incorrect username or password.` error and these logs
![Screenshot from 2022-03-09 13-41-05](https://user-images.githubusercontent.com/32527347/157435122-d98657df-8cfb-4bb5-81d5-f04243bb8d75.png)

**Comment by Omarabdul3ziz** [comment]
on a peertube instance deployed from the weblet: https://pt111ptest.gent01.dev.grid.tf/
but other ids can login on the same instance.

**Comment by asamirr** [comment]
Facing same issue here while trying to login on a taiga instance on mainnet! 
![image](https://user-images.githubusercontent.com/9322121/157658943-e8f83943-ab77-4c4e-a5dd-2443f4a9910a.png)

**Comment by ken-de-moor** [comment]
Linked comment says issue is solved on TF Connect side.
