### ISSUE TITLE
T&S link is broken.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#417]
Issue is not actually in the app, see https://github.com/threefoldtech/home/issues/1191

Next app update we'll update link to https://library.threefold.me/info/legal/#/

**Comment by ken-de-moor** [comment]
Fixed in settings, not fixed in wizard. I assume wizard is a separate deploy? Will we make sure we don't forget this?

**Comment by LennertDefauw1** [comment]
WIzard is indeed seperate deploy
