### ISSUE TITLE
Settings has fingerprint option, but I don't have fingerprint on my device.

### ISSUE THREAD

**Issue by ken-de-moor** [threefoldtech/threefold_connect#421]
Both in staging and production.

I have facial recognition, and that's the actual thing being enabled when I enable this option, however everywhere it references it as "fingerprint".

**Comment by AlaaElattar** [comment]
- I tested it with my iphone which doesn't contain a fingerprint, it worked right and was referenced as `Face ID`.

**Comment by khaledyoussef24** [comment]
verified on version 3.9.2
device with finger print (touch id)
![Image](https://github.com/user-attachments/assets/bb8efc09-ecb0-4480-9487-284a20bec63b)
device without finger print (faceid)
![Image](https://github.com/user-attachments/assets/3cc7ade5-9da7-48b4-80b2-ff7738294ba4)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407478#case_4050873)
[testcase2](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407478#case_4050874)
