### ISSUE TITLE
Change wording in introscreen app: Start your ThreeFold Journey

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#440]
I agree to ThreeFold's Terms and Conditions (CAPITALS MATTER PEOPLE) 
and would be best to have this sentence in one line with checkbox right from it or (if not possible) underneath it. Outlining is a bit weird now.

**Comment by AlaaElattar** [comment]
- That's the new version of the wizard  https://github.com/user-attachments/assets/9d6c38e7-d4b7-4722-ad8f-2efa2eca5049
- Please check the new design if u have any comments.

**Comment by sabrinasadik** [comment]
### Welcome to ThreeFold
- ThreeFold Connect (capital F) is your main access point to the ThreeFold Grid (I would remove and more. This is good to use after a list. ThreeFold Grid is a single item and it's a bit strange to add 'and more' to it. So either stop there, or say 'to the ThreeFold Grid, the ThreeFold Token, and more)

### Maximum security
- 2x provides, doesn't feel right. This app provides a secure authentication mechanism that creates your virtual identity on the ThreeFold Grid.
- ThreeFold Grid (capital F)

### ThreeFold Wallet
- Access your ThreeFold Wallet and send/receive ThreeFold Tokens (TFT).
- More currencies can be added in the future.

### ThreeFold News
- Stay up to date with ThreeFolds' latest news.

### Start your ThreeFold journey
- Space missing between start and your
- Change the button to 'Lets Go'
- I agree to ThreeFolds' (capital F) Terms & Conditions


A couple of take-aways:

- Be consistent with capitals. ThreeFold.
- ThreeFolds' = possessive ThreeFold's = ThreeFold is 
- Try not to use the same words in the same sentence twice. E.g. 2x provides or 2x start.


That's all I can see in the video, please let me know when / where I can review the rest.

**Comment by AlaaElattar** [comment]
### Work Completed :
Requested changes applied.

@sabrinasadik  please check if u have more comments.

https://github.com/user-attachments/assets/b2f1be0e-859d-4a16-8e36-a1156c09ed9d

**Comment by sabrinasadik** [comment]
### Welcome to

- still says **Threefold** Grid and **Threefold** Token ==> please make sure this says ThreeFold and that we pay attention to capitals

### ThreeFold News 
- Add a . at the end of the sentence

### Start your journey
- I agree to **ThreeFolds'** Terms & Conditions

**Comment by khaledyoussef24** [comment]
verified ![Image](https://github.com/user-attachments/assets/a5488c5c-8a55-4a50-a794-874ca0decb4f)

**Comment by khaledyoussef24** [comment]
verified
![Image](https://github.com/user-attachments/assets/ece59561-653b-4911-8c81-0e3b96740181)
![Image](https://github.com/user-attachments/assets/0d001eca-c4e4-455b-8b4c-eb8eb8a95299)
![Image](https://github.com/user-attachments/assets/107c51c3-c6c9-4425-9c2e-fd586edb029e)
![Image](https://github.com/user-attachments/assets/e71fe56e-b73c-4e68-b7cf-3c25febe9ffd)
![Image](https://github.com/user-attachments/assets/9a67f4a6-4f60-475a-95b7-c8613b225cb3)

**Comment by ramezsaeed** [comment]
space missing in the first line between "START"  and "YOUR" !!

![Screenshot from 2024-10-23 22-30-22](https://github.com/user-attachments/assets/dca61650-6d0c-4538-98fd-6eef87548ca8)

**Comment by AlaaElattar** [comment]
It's handled but not in the testing deployed version yet.

**Comment by khaledyoussef24** [comment]
verified 
version 3.9.1
apk 30-10-2024
android 15
![Image](https://github.com/user-attachments/assets/ba4d2026-7c0d-41e5-964f-e1717ee10dcc)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407468#case_4409420)
