### ISSUE TITLE
Unable to authenticate to open wallet or use TFA on Android

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/threefold_connect#478]
User reports seeing screens as shown below. Cannot access wallet. Android 16 on Pixel 6 Pro.

![image](https://user-images.githubusercontent.com/17682591/180337444-83839aa2-b23a-4f16-8c7d-83d487120fea.png)
![image](https://user-images.githubusercontent.com/17682591/180337451-e1e6ccc3-3c2b-49cb-a73b-45138d618606.png)

**Comment by LennertDefauw1** [comment]
Using Android 13 (latest beta version) and Pixel 6 and still cant reproduce the issue. 

Android 16 is not released yet.

Does this issue still persist? @scottyeager

**Comment by scottyeager** [comment]
Thanks @LennertDefauw1. User is indeed running Android 13, my mistake. I've inquired with him on whether the issue persists and will report back.
