### ISSUE TITLE
Named key derivation

### ISSUE THREAD

**Issue by LennertDefauw1** [threefoldtech/threefold_connect#479]
It should be possible to send the following scope:

``` 
{
   "namedDerivedSeed" : { "value": true, "name" : "walletSeed"}
}
```
(or something like that), and obtain the derived seed based on that name

This is used to have keys across different domains

**Comment by ken-de-moor** [comment]
- Seperate APK for staging has been built.

**Comment by ken-de-moor** [comment]
Multiple derived seeds
