### ISSUE TITLE
Farmer section keeps loading 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#480]
{
  "level": "error",
  "args": [
    "[ERROR] Request failed with status code 400: POST https://graph.grid.tf/graphql"
  ],
  "timestamp": "2022-08-01T12:48:54.857Z"
}

{
  "level": "error",
  "args": [
    "[ERROR] TypeError: undefined is not an object (evaluating 'oT.value.filter')"
  ],
  "timestamp": "2022-08-01T12:48:54.863Z"
}

{
  "level": "error",
  "args": [
    "[ERROR] 2022-08-01 14:51:08",
    "       RPC-CORE:",
    "health(): Health:: disconnected from wss://tfchain.grid.tf: 1006:: Abnormal Closure"
  ],
  "timestamp": "2022-08-01T12:51:08.233Z"
}

{
  "level": "error",
  "args": [
    "[ERROR] 2022-08-01 14:51:16",
    "         API-WS:",
    "disconnected from wss://tfchain.grid.tf: 1006:: Abnormal Closure"
  ],
  "timestamp": "2022-08-01T12:51:16.458Z"
}

**Comment by LennertDefauw1** [comment]
Seems like a caching problem, temporary solution is delete cache of the app, researching for a better solution. Ill keep u updated

**Comment by sabrinasadik** [comment]
Is there a better solution by now?

**Comment by LennertDefauw1** [comment]
Cache problem is fixed and live @sabrinasadik
