### ISSUE TITLE
User unable to recover account using seed phrase and 3bot name.

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/threefold_connect#485]
The user claims he is using the correct 3bot name and seed phrase, but is unable to recover the account. He claims he used the same information back in 2020 and was able to recover it then. Quoting:

"i know for sure that this name is correct because since then i had attempted to recover my account on a newer phone in 2020 and it worked. but now i am using the exact same details and i am having absolutely 0 luck accessing my account".

I requested him to verify the 3bot name by checking email address verification from info@openkyc.live, but he says he did receive an email:

"I've just scrolled through my email all the way back to 20/07/2019 which is when i know for sure my account was created because that was the night i met Adnan in Lebanon, but nothing was received from info@openkyc.live

![Screenshot_20220823-005810_Outlook](https://user-images.githubusercontent.com/105203696/185978395-0847306a-8dcf-4eb7-9e72-329d26b492c7.jpg)

![Screenshot_20220823-012915](https://user-images.githubusercontent.com/105203696/185978431-8f5456d1-ccef-4396-a93d-cf6366554a4a.jpg)

**Comment by robvanmieghem** [comment]
will check the conversion

**Comment by robvanmieghem** [comment]
The adress has not been activated nor is there a trustline to tft:

https://stellar.expert/explorer/public/search?term=GD6BJ7C4MAD27T5GZYJJAQSUE3O6WXAMQ5RCSTN4XZT4FYFZTOSGS5SO

**Comment by TullysInc** [comment]
Hello @robvanmieghem

Does the address activation here involve your intervention to ensure the transferring of tokens from Rivine?

**Comment by LennertDefauw1** [comment]
Migration from revine to stellar is not available in v3, will need to put him back on v2, could you provide me his telegram handle so I could follow up with him?

**Comment by robvanmieghem** [comment]
Tomorrow I'll put the conversion service back online but only with the activation enabled, I'll do the actual migration manually.

**Comment by TullysInc** [comment]
Hi @ LennertDefauw1 - I reached out to the user requesting the information. I will share with you when available at hand.

**Comment by TullysInc** [comment]
@LennertDefauw1

Here’s the customer Adam’s TG handle - Adamd7

He’s generally available to talk at 11pm AEST (3pm CEST). Otherwise too, you can leave him an offline message and he will get back to you with a response. Please let me know if you need anything else.

**Comment by LennertDefauw1** [comment]
@robvanmieghem 


https://stellar.expert/explorer/public/account/GD6BJ7C4MAD27T5GZYJJAQSUE3O6WXAMQ5RCSTN4XZT4FYFZTOSGS5SO

Trustlines have been added, can you migrate the account manually?

**Comment by robvanmieghem** [comment]
Thank you. Yes, I can migrate now.

**Comment by robvanmieghem** [comment]
@TullysInc The migration has been executed.

**Comment by TullysInc** [comment]
@robvanmieghem and @LennertDefauw1  - Thank you both for your assistance with this ticket. I appreciate your help.

**Comment by TullysInc** [comment]
Hello @robvanmieghem

The farmer claims he had invested in 10M tokens and not 2500 as shown in the balance here: https://stellar.expert/explorer/public/account/GD6BJ7C4MAD27T5GZYJJAQSUE3O6WXAMQ5RCSTN4XZT4FYFZTOSGS5SO

Would you be able to investigate the Rivine address to arrive at a concrete conclusion? I'd appreciate your help.

**Comment by robvanmieghem** [comment]
Stellar address `GD6BJ7C4MAD27T5GZYJJAQSUE3O6WXAMQ5RCSTN4XZT4FYFZTOSGS5SO`  corresponds to the old tfchain address `013470b707da4355184d657bf59a09e8d11f4f3d8d1320886b108da4d23ba2dc2ebfa72684eddf`.
On that explorer you can see that there are only 2500 TFT : https://explorer2.threefoldtoken.com/hash.html?hash=013470b707da4355184d657bf59a09e8d11f4f3d8d1320886b108da4d23ba2dc2ebfa72684eddf

**Comment by scottyeager** [comment]
Was it possible in the Rivine days to derive multiple wallets from the same seed? Maybe the funds are on another derivation path?

**Comment by sabrinasadik** [comment]
Discussed with Adnan. Please direct all communication with this user to me.
