### ISSUE TITLE
Present valid wallets as options when adding a payout address to imported farm

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/threefold_connect#486]
Users who create farms in the Dashboard may want to have them visible in the app. To do so, they currently import the wallet seed associated with the TF Chain account that owns the farm.

If the farmer didn't set a payout address before importing the wallet, they will see an option to add payout address on the farming screen. Currently, this sets it to the Stellar address associated with the same wallet that owns the farm on TF Chain. The problem is that these wallets might not be activated and have a trustline to TFT (in most cases they probably don't).

Instead, the user could see a list of valid wallets within their app to choose from. This would provide a better experience and avoid surprises for farmers on minting day when their payout address can't receive TFT.

**Comment by sabrinasadik** [comment]
@LennertDefauw1 Is this possible? If yes, can this be planned pls

**Comment by LennertDefauw1** [comment]
This feature is possible. Currently we have an update still in QA which will have major performance improvements. When this version is released on main, this feature can be planned.

**Comment by LennertDefauw1** [comment]
Closing and moving to the right repository.
