### ISSUE TITLE
Scanning Stellar wallet QRs doesn't work

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/threefold_connect#488]
Scanning Stellar wallet QR codes doesn't fill the "To" wallet address field as expected in the send coins section of the wallet. Tested with QRs from StellarX and StellarTerm.

This was reported by the community and I reproduced on iOS, app version 3.7.2 - 170.

Steps:

1. Select a wallet, choose Stellar as chain, and hit Scan QR
2. Scan a Stellar wallet QR as provided by [StellarX](https://www.stellarx.com/deposit) or StellarTerm (see screenshot below)
3. Code is scanned, but address does not fill

Example QR:
![image](https://user-images.githubusercontent.com/17682591/191087194-deecc32b-a037-4852-bec1-baa11ee6b643.png)

**Comment by LennertDefauw1** [comment]
There isn't really a generic component made in Scan QR inside the ThreeFold wallet. 

We only support created QR codes made in the 'Receive' screen of the wallet. 

This can be implemented, but has to be planned.

**Comment by scottyeager** [comment]
Thanks for the insight @LennertDefauw1

I think the immediate issue in that case is providing a clearer user experience when an unsupported QR is scanned. A simple pop up explaining that the functionality isn't yet supported, for example.

**Comment by LennertDefauw1** [comment]
Okay, will make an issue :)

**Comment by LennertDefauw1** [comment]
https://github.com/threefoldtech/threefold_connect/issues/489#issue-1380499808

**Comment by LennertDefauw1** [comment]
switched to wallet-next
https://github.com/threefoldtech/wallet-next/issues/188

**Comment by scottyeager** [comment]
Thanks :)
