### ISSUE TITLE
Remove 3bot name in recover process since this is redundant data

### ISSUE THREAD

**Issue by LennertDefauw1** [threefoldtech/threefold_connect#504]

**Comment by zaelgohary** [comment]
> the 3bot name is still there 
![Image](https://private-user-images.githubusercontent.com/110984055/379371237-f29a164c-bc1a-4e69-ae30-55803a566e24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTY5MTMsIm5iZiI6MTczMDcxNjYxMywicGF0aCI6Ii8xMTA5ODQwNTUvMzc5MzcxMjM3LWYyOWExNjRjLWJjMWEtNGU2OS1hZTMwLTU1ODAzYTU2NmUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMDM2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWEyNjhmYzcxYzE3ZmNjMmY3NTEzZTdmZDQ2N2ZlMWRhMGIwNWQ0N2M2ZWY1OTFkYWRiM2Q1ZTkyNDc1MTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.grGYlLFsdtkE-at-pHRTtTix2Z763tl0hOZKxyckH_U)

Should be done [here](https://github.com/threefoldtech/threefold_connect/pull/707)

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- 3Bot name has been removed
