### ISSUE TITLE
Farming Section of App Is not loading! 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/threefold_connect#505]
![image](https://user-images.githubusercontent.com/44621168/202867852-e9c78ee6-807b-46ec-ba5a-42d9ffdfbb87.png)

I Tested and was able to replicate the problem, It never stops loading, when clicking farming from the side access bar. 

Im on iphone 11 pro max up-to-date, 

on threefold-connect version 3.7.3 - 172 
My farm is 2914 and is not loading

![480EE03C-B118-46D8-B605-B6FC4622E06C](https://user-images.githubusercontent.com/44621168/202867969-0dfd5874-6b9f-4e66-a3ec-04d86664b0d1.png)
![7A8ECE30-554F-4E2C-B24A-6E1F21E41ABA](https://user-images.githubusercontent.com/44621168/202867971-9859c056-8f5d-4bcc-a681-4fd0a16852a6.png)

**Comment by Parkers145** [comment]
Copy of logs


 > [
  {
    "level": "info",
    "args": [
      "[INFO] running version: "
    ],
    "timestamp": "2022-11-20T05:41:34.167Z"
  },
  {
    "level": "log",
    "args": [
      "[LOG] Running on version: ",
      "farmer-v3.1.9"
    ],
    "timestamp": "2022-11-20T05:41:34.344Z"
  },
  {
    "level": "log",
    "args": [
      {
        "flagsmithEnv": "VGR7Kmd6qWqnYaZxXU7Gyw"
      }
    ],
    "timestamp": "2022-11-20T05:41:34.538Z"
  },
  {
    "level": "table",
    "args": [
      {
        "flags": {
          "vesting": {
            "id": 13,
            "enabled": false,
            "value": null
          },
          "transactionoverview": {
            "id": 14,
            "enabled": true,
            "value": null
          },
          "pkid-url": {
            "id": 18,
            "enabled": true,
            "value": "https://pkid.jimber.org"
          },
          "stellar-url": {
            "id": 19,
            "enabled": true,
            "value": "https://horizon.stellar.org"
          },
          "currencies": {
            "id": 43,
            "enabled": true,
            "value": "[\n    {\n        \"name\":\"TFT\",\n        \"asset_code\":\"TFT\",\n        \"type\": \"stellar\",\n        \"issuer\":\"GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47\"\n    },\n    {\n        \"name\":\"TFT\",\n        \"asset_code\":\"TFT\",\n        \"type\": \"substrate\",\n        \"issuer\":\"GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47\"\n    },    \n    {\n        \"name\":\"BTC\",\n        \"asset_code\":\"BTC\",\n        \"type\": \"stellar\",\n        \"issuer\":\"GCNSGHUCG5VMGLT5RIYYZSO7VQULQKAJ62QA33DBC5PPBSO57LFWVV6P\"\n    },\n    {\n        \"name\":\"TFTA\",\n        \"asset_code\":\"TFTA\",\n        \"type\": \"stellar\",\n        \"issuer\":\"GBUT4GP5GJ6B3XW5PXENHQA7TXJI5GOPW3NF4W3ZIW6OOO4ISY6WNLN2\"\n    },\n    {\n        \"name\":\"FreeTFT\",\n        \"asset_code\":\"FreeTFT\",\n        \"type\": \"stellar\",\n        \"issuer\":\"GCBGS5TFE2BPPUVY55ZPEMWWGR6CLQ7T6P46SOFGHXEBJ34MSP6HVEUT\"\n    }\n]"
          },
          "stellar-network": {
            "id": 44,
            "enabled": true,
            "value": "Public Global Stellar Network ; September 2015"
          },
          "threefold-service-url": {
            "id": 45,
            "enabled": true,
            "value": "https://tokenservices.threefold.io/threefoldfoundation"
          },
          "fee-destination": {
            "id": 46,
            "enabled": true,
            "value": "GAAN2EVASE724NRZWDKPW57NVSGIJZHVEDSSAJ7PKYIS2D26OEUYXGX3"
          },
          "fee-amount": {
            "id": 47,
            "enabled": true,
            "value": "0.1000000"
          },
          "can-move-wallets": {
            "id": 73,
            "enabled": false,
            "value": null
          },
          "farm_terms_and_conditions_url": {
            "id": 78,
            "enabled": true,
            "value": "https://library.threefold.me/info/legal/#/tfgrid/legal__terms_conditions_tfgrid3"
          },
          "tfchain_endpoint": {
            "id": 80,
            "enabled": true,
            "value": "wss://tfchain.grid.tf"
          },
          "tfchain_activation_base_url": {
            "id": 81,
            "enabled": true,
            "value": "https://activation.grid.tf"
          },
          "can_create_wallet_for_farmer": {
            "id": 82,
            "enabled": false,
            "value": null
          },
          "always-migrate-pkid": {
            "id": 84,
            "enabled": false,
            "value": null
          },
          "can_create_farms_for_farmer": {
            "id": 85,
            "enabled": true,
            "value": null
          },
          "supported-currencies": {
            "id": 86,
            "enabled": false,
            "value": "[{\n\t\t\"name\": \"TFT\",\n\t\t\"asset_code\": \"TFT\",\n\t\t\"type\": \"stellar\",\n\t\t\"issuer\": \"GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47\",\n\t\t\"fee\": 0.1\n\t},\n\t{\n\t\t\"name\": \"TFT\",\n\t\t\"asset_code\": \"TFT\",\n\t\t\"type\": \"substrate\",\n\t\t\"issuer\": \"GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3\",\n\t\t\"fee\": 0.01\n\n\t},\n\t{\n\t\t\"name\": \"TFTA\",\n\t\t\"asset_code\": \"TFTA\",\n\t\t\"type\": \"stellar\",\n\t\t\"issuer\": \"GBUT4GP5GJ6B3XW5PXENHQA7TXJI5GOPW3NF4W3ZIW6OOO4ISY6WNLN2\",\n\t\t\"fee\": 0.1\n\t},\n\t{\n\t\t\"name\": \"FreeTFT\",\n\t\t\"asset_code\": \"FreeTFT\",\n\t\t\"type\": \"stellar\",\n\t\t\"issuer\": \"GCBGS5TFE2BPPUVY55ZPEMWWGR6CLQ7T6P46SOFGHXEBJ34MSP6HVEUT\",\n\t\t\"fee\": 0.1\n\n\t}\n]"
          },
          "stellar-bridge-address": {
            "id": 89,
            "enabled": false,
            "value": "GBNOTAYUMXVO5QDYWYO2SOCOYIJ3XFIP65GKOQN7H65ZZSO6BK4SLWSC"
          },
          "tfchain_graphql_endpoint": {
            "id": 90,
            "enabled": true,
            "value": "https://graph.grid.tf/graphql"
          },
          "bridge-fees": {
            "id": 94,
            "enabled": false,
            "value": "[\n  {  \n  \"from\": \"stellar:TFT\",\n  \"to\": \"substrate:TFT\",\n  \"fee\": 1\n  }\n]"
          },
          "can_bridge_stellar_substrate": {
            "id": 96,
            "enabled": false,
            "value": null
          },
          "locked-tokens": {
            "id": 99,
            "enabled": false,
            "value": null
          },
          "can-see-danger-zone": {
            "id": 135,
            "enabled": true,
            "value": null
          },
          "can-delete-wallet": {
            "id": 136,
            "enabled": true,
            "value": null
          },
          "refresh-balance-in-milliseconds": {
            "id": 137,
            "enabled": false,
            "value": 5000
          },
          "authenticator_backend": {
            "id": 139,
            "enabled": false,
            "value": "https://login.staging.jimber.io/api/users"
          },
          "friendbot-url": {
            "id": 147,
            "enabled": false,
            "value": "https://friendbot.stellar.org"
          }
        }
      }
    ],
    "timestamp": "2022-11-20T05:41:36.328Z"
  },
  {
    "level": "table",
    "args": [
      [
        {
          "type": "NATIVE",
          "name": "Daily",
          "index": 0,
          "seed": "*********************"
        }
      ]
    ],
    "timestamp": "2022-11-20T05:41:37.108Z"
  },
  {
    "level": "error",
    "args": [
      "[ERROR] TypeError: undefined is not an object (evaluating 'BM.value.filter')"
    ],
    "timestamp": "2022-11-20T05:41:40.521Z"
  },
  {
    "level": "error",
    "args": [
      "[ERROR] TypeError: undefined is not an object (evaluating 'BM.value.filter')"
    ],
    "timestamp": "2022-11-20T05:41:54.753Z"
  }
]

**Comment by Parkers145** [comment]
Sorry 1956, 2914 was a node I’d

**Comment by LennertDefauw1** [comment]
Solved and live on beta / main.
