### ISSUE TITLE
News tab not loading on ios

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/threefold_connect#515]
Attempted network reset
Force restarted the app

only able to get the blank screen 
![5AD08C58-ECF0-4D7C-A88F-FF8E11474C36](https://user-images.githubusercontent.com/44621168/208265027-1c540513-37d1-490b-8038-02a4511c8bec.png)

**Comment by LennertDefauw1** [comment]
SSL cert was expired and renew bot didn't notice it. Is already fixed.
