### ISSUE TITLE
TF Connect-StellarChain to Playground-TFChain Fees Could be Announced

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/threefold_connect#519]
When we transfer TFT from TF Connect to the Playground, it costs 1 TFT. It could be announced here under 
> Scan code using Threefold connect to send tokens

![Screen Shot 2023-01-12 at 1 11 08 AM](https://user-images.githubusercontent.com/77026219/211991072-7d59ded0-a7f8-4869-8172-2e05b3214640.png)

As is it now, on TF Connect is says the max fee is 0.1 TFT so it is kind of misleading.

(Possible) Additional text:

> Note that it costs 1 TFT to transfer tokens from TF Connect and Stellar Chain to the Playground and TFChain.

**Comment by AhmedHanafy725** [comment]
the shouldn't know anything about the address of TFchain bridges, it's an address for the app
