### ISSUE TITLE
Remove migration option from app 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#522]
We have removed all V2 infrastructure from our side. Thus migration through the app will not be possible. 

Please remove the feature.

**Comment by ken-de-moor** [comment]
What error handling should we have, or what do we display when the user still has V2 farms? Do we just filter them out entirely and act as they don't exist and only load in V3 farms? @sabrinasadik

**Comment by sabrinasadik** [comment]
Only load V3 farms.
Change messaging to:

Your TF Farms 
- Farms connected to your existing wallets

**Comment by ken-de-moor** [comment]
Live right now. Make sure to restart the app if you still see the old version. Cache is the devil
