### ISSUE TITLE
User can't log into forum using Firefox and TF Connect on Android

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/threefold_connect#528]
User reports that they can't login to forum.threefold.io in the Firefox browser (v110.0.1) running on Linux using the TF Connect app on Android. 

I tested using the same version of Firefox also running on Linux and was not able to reproduce using my iOS TF Connect app.

User also tested in a private windows and with a new profile.

**Comment by zaelgohary** [comment]
I tried and didn't encounter the same issue. Could you check if the issue persists?

**Comment by zaelgohary** [comment]
The issue happens when the verified email in TF Connect differs from the one used in the Forum. Will move to verification as the issue is not from our side.

**Comment by atefnazmy** [comment]
- The Issue is still reproducible.
- The Forum should automatically use the email address retrieved from the authenticated TF Connect account. 

https://github.com/user-attachments/assets/38ef4fb9-7e35-4db0-8449-b5091b953730


- Android Version: Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024

**Comment by zaelgohary** [comment]
> - The Issue is still reproducible.
> 
> - The Forum should automatically use the email address retrieved from the authenticated TF Connect account. 
> 
> 
> 
> https://github.com/user-attachments/assets/38ef4fb9-7e35-4db0-8449-b5091b953730
> 
> 
> 
> 
> 
> - Android Version: Android 14,
> 
> - Threefold-Connect: 4.0.0-184
> 
> - APK:12-12-2024

Issue can't be fixed from our side. You may open an issue in forum's repo.
