### ISSUE TITLE
Attachment icon in Support chat crashes the app.

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/threefold_connect#531]
When attempting to attach a file in Support chat, the app crashes on Android OS.

Tested with Android 13, TF app ver: 3.7.3

https://user-images.githubusercontent.com/105203696/230029414-88290fff-e8d7-443c-a332-207788495028.mp4

On a 2nd attempt I received this runtime error notification:

![Support_TF App runtime error](https://user-images.githubusercontent.com/105203696/230029549-5926ceb4-e6f2-443a-a47f-516814c97a5b.jpg)

However, the attachment icon appears to work fine with iOS.

Tested with iOS 15.7.3

https://user-images.githubusercontent.com/105203696/230030270-58f56374-ec49-4ae6-b9a4-fdf8a1b6031d.mp4

**Comment by TullysInc** [comment]
Hi @LennertDefauw1 @ken-de-moor  - Request you to have a look, please.

**Comment by amandacaster** [comment]
https://github.com/threefoldtech/threefold_connect/assets/88147124/24bed95f-3acc-4983-a3c5-d954b3d3885f

**Comment by Mahmoud-Emad** [comment]
after some debugging seems to be no issues found, Is it possible to be a connection issue?

![image](https://github.com/threefoldtech/threefold_connect/assets/57001890/9d13605d-8fdb-4583-912c-8aba8a9f16c1)

**Comment by TullysInc** [comment]
> after some debugging seems to be no issues found, Is it possible to be a connection issue?

I find it strange that it works for some, and not a majority of users. Besides 3 reports from the Support team, we have farmers across geographical boundaries confirming the app crashes, so I would rule out connectivity as a probable cause.

**Comment by Mahmoud-Emad** [comment]
Update: The issue has been resolved by re-installing the app. It appears that there may have been a problem with the previous version of the device's webView when the app was initially installed, and the subsequent update caused a conflict with the existing webView used in the app. To address this, we recommend informing our users to follow the same steps. If anyone encounters any issues with the app, they should uninstall it and then reinstall it again to check if the problem persists.

**Comment by TullysInc** [comment]
Closing this issue.
