### ISSUE TITLE
TF Connect App - Unavailable in App Store

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/threefold_connect#532]
iOS users have confirmed the TF Connect App is unavailable for download in the App store.

https://apps.apple.com/us/app/3bot-login/id1459845885

![iOS App Store TF Connect](https://user-images.githubusercontent.com/105203696/233054437-43a9b2ae-e9a0-4448-bfbc-702e26e89c87.jpg)

@sabrinasadik - Please review and advise.

**Comment by sabrinasadik** [comment]
Where are they located?

**Comment by TullysInc** [comment]
Issue Resolved.
