### ISSUE TITLE
Farm Creation in App results as a prolonging error

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/threefold_connect#534]
Both; Android and iOS users have reported issues with Farm creation in TF Connect. Tested these individually and these are the results.:

Tested with Iphone 7plus (15.7.3), TF Connect app version: 3.7.3 – 172

On first attempt; page is stuck at "Getting Terms and Conditions" with no further progress.
https://github.com/threefoldtech/threefold_connect/assets/105203696/83ab22cc-9159-437a-b5fc-b52cdc77e286

On 2nd attempt, page is stuck at "Creating Twin"
https://github.com/threefoldtech/threefold_connect/assets/105203696/3d026fa9-7b66-4da9-8cef-04f5b103851e

Android test: Android 13, TF Connect app version: 3.7.3 – 172
![Android 13](https://github.com/threefoldtech/threefold_connect/assets/105203696/bea2dc14-0443-45c9-ac9b-5a31cc2d4152)

Page is stuck at "Getting Terms and Conditions" with no further progress.

**Comment by Mahmoud-Emad** [comment]
The issue identified pertains to the JavaScript wallet and farmers plugin. It appears to be a syncing problem. Specifically, the issue occurs during the creation of a new farm. When calling the "createAccount" method, we are currently passing only the public key, whereas the technique now expects to receive both the public key and the relay. This mismatch in parameter expectations leads to the encountered issue. To resolve this, we need to update the code to include the relay parameter when invoking the "createAccount" method during farm creation.

**Comment by Mahmoud-Emad** [comment]
The issue should be solved now 

https://github.com/threefoldtech/threefold_connect/assets/57001890/88f8be2c-4ad9-4415-9228-9efd342eab2f

**Comment by TullysInc** [comment]
Tested. Works fine.
