### ISSUE TITLE
too empty landing screen

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#536]
![image](https://github.com/threefoldtech/threefold_connect/assets/64129/255fdac6-6d41-4604-b966-d06ae7cb2341)

Maybe few items from the menu should be shown up on the screen e.g wallet, farming, news, support

**Comment by AhmedHanafy725** [comment]
maybe we can use this welcoming screen while checking the services instead of the current one. Then switch to a screen with a grid view for wallet, farm, news, ...

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)

- Research to create artwork for Splash screen work with both light and dark mode
- think of a new Home page concept containing links to other pages

**Comment by ehab-hassan** [comment]
Work in Progress (WIP) 
ll update soon

**Comment by ehab-hassan** [comment]
need to be near the dashboard theme 
not finish yet I think need some img
![Frame 427320924](https://github.com/threefoldtech/threefold_connect/assets/10484295/b81f307b-3483-4c4b-8103-f805a7216532)

animation here
https://www.figma.com/proto/Y17fOEbL8KLRkwzm9TqkBv/TF-Connect?type=design&node-id=20-28&t=FM3vUkoa3RqN9Ofe-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=20%3A28

**Comment by ehab-hassan** [comment]
@AhmedHanafy725 please check

**Comment by AhmedHanafy725** [comment]
looks great 🎉

**Comment by ehab-hassan** [comment]
@AhmedHanafy725 
primary color(same as dashboard) #1AA18F 
secondary color(same as dashboard) #74DDC3

![map](https://github.com/threefoldtech/threefold_connect/assets/10484295/d8bd439f-5106-4509-bd10-22bc8bed94de)

**Comment by khaledyoussef24** [comment]
verified the new landing page home looks better and loading screen at the first with splash motion to the logo
![Image](https://github.com/user-attachments/assets/a1dc135c-2eec-47f7-99a9-a5c95319026c)

**Comment by xmonader** [comment]
While the page ain't as empty as it used to be, but the tablet screenshot isn't good at all. @khaledyoussef24 please open a separate ticket for tablets.
