### ISSUE TITLE
Check if the added email is currently in use by another account

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/threefold_connect#539]
### Description

Currently there's no check while creating an account if the email is already in use or not, and the same email can be used by multiple accounts.

https://github.com/threefoldtech/threefold_connect/assets/101194226/93c0822a-3036-4643-a758-47247dcfd1f2

### Environment

- Android Version: `13`
- Threefold Connect version: `3.7.3 - 173`

**Comment by AhmedHanafy725** [comment]
let's check if we can know if the email was registered before or not, if not let's move to 3.15
