### ISSUE TITLE
Email validation is not working correctly

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/threefold_connect#541]
### Description

Email validation is not working correctly, The email field in the signup page and in the identity page accepts invalid email formats. the fields currently accepts any sting that has `@` between any 2 characters.

https://github.com/threefoldtech/threefold_connect/assets/101194226/baf044a9-abf7-4b5d-bad4-b85f7ffb14b0

https://github.com/threefoldtech/threefold_connect/assets/101194226/7094a8e3-5ba2-429c-9752-d57b5b1a1367

Environment
- Android Version: `13`
- Threefold Connect version: `3.7.3 - 173`

**Comment by AlaaElattar** [comment]
### Work Completed:
- Updated regex of email validation.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Email validation is working fine.

https://github.com/user-attachments/assets/12dda88a-19e3-44a9-9bb1-672b68ea70a1

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407469#case_4044803
