### ISSUE TITLE
Improve the account recovery experience

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/threefold_connect#543]
### Description

After successfully recovering an account the user gets redirected to an empty page that mentions that the account was recovered successfully. in this page there's no option to close it and it doesn't disappear automatically after a couple of seconds. and there's no way to close it other than pressing the `back` button on the upper left corner which isn't really user friendly since the user didn't choose to navigate to this page from the start.

https://github.com/threefoldtech/threefold_connect/assets/101194226/f8d43ecd-93a8-41f8-b286-4e14e876a854

a better experience would be showing a popup with the same message and the user should be redirected to the home page after the account recovery.

### Environment

- Android Version: `13`
- Threefold Connect version: `3.7.3 - 173`

**Comment by khaledyoussef24** [comment]
verified could recover the account smoothly
![Image](https://github.com/user-attachments/assets/fa32753c-b9c2-48b8-8a9f-c6c085865f3d)
insert your old seeds and name
![Image](https://github.com/user-attachments/assets/e975612a-0606-43e1-b296-1511e240485f)
![Image](https://github.com/user-attachments/assets/d542c951-12e2-442b-95fc-36767a6d9756)
![Image](https://github.com/user-attachments/assets/e7901698-4f11-4a7d-b594-3d7252459a95)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407470#suite_section_407470)
