### ISSUE TITLE
Recover Account: Title and placeholder improvements

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/threefold_connect#544]
### Description

The fields and placeholders in the `Recover Account` page should be capitalized instead of being all in uppercase.

`NAME` -> `Name`
`SEED PHRASE` -> `Seed Phrase`

![image](https://github.com/threefoldtech/threefold_connect/assets/101194226/fd7888e5-7a93-41e9-afa4-b653060363db)

![image](https://github.com/threefoldtech/threefold_connect/assets/101194226/7306243f-9ff3-40ae-acfd-bce1ae483457)

### Environment

- Android Version: `13`
- Threefold Connect version: `3.7.3 - 173`

**Comment by khaledyoussef24** [comment]
verified 
Titles are not all capitalized now
![Image](https://github.com/user-attachments/assets/84cde5ad-f9d3-401f-be61-b14aad3948e1)
