### ISSUE TITLE
News: add reload functionality

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/threefold_connect#545]
### Description

The news page is missing refresh functionality to load new articles. a good implementation would be swiping down to reload the page, or having a reload button in the upper right corner.

https://github.com/threefoldtech/threefold_connect/assets/101194226/99515617-28ad-4967-92ad-233d357efefb

### Environment

- Android Version: `13`
- Threefold Connect version: `3.7.3 - 173`

**Comment by zaelgohary** [comment]
Now, swiping down reloads more articles.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0 -184
- APK:12-12-2024
- Currently reload functionality has been successfully added and swiping down reloads more articles.


https://github.com/user-attachments/assets/e20adcc9-bbd9-47c9-bc8f-e65c38beec89


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407472#case_4048995
