### ISSUE TITLE
Add an option to copy the seed phrase

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/threefold_connect#546]
### Description

A button should be added to copy the seed phrase while creating the account or in the settings page since the only option to save the phrase is by manually writing it or taking a screenshot and both options might lead to losing it or writing a wrong phrase in the future.

or it should be copied if the user clicked on the phrase.

![image](https://github.com/threefoldtech/threefold_connect/assets/101194226/ddbdd645-e2c0-4814-a7f4-c3e5e5e7bc23)

![image](https://github.com/threefoldtech/threefold_connect/assets/101194226/cb4edbe6-eae7-4762-b636-f0f25a09b2f9)

### Environment

- Android Version: `13`
- Threefold Connect version: `3.7.3 - 173`

**Comment by ken-de-moor** [comment]
FYI you can tap 5 times to copy, hidden feature. In general we didn't want users to have an easy copy as it'd make sure people don't have a written copy and can easily lose access if they just lose their phone (since the phone would be the single source of having the seed phrase).
