### ISSUE TITLE
[Bug 🐞]: Threefold Connect: Recover Account should validate the data before making the request

### ISSUE THREAD

**Issue by MahmoudRedaSayed** [threefoldtech/threefold_connect#548]
### What happened?

When u enter the Application and click on the Recover button there will be a from required the username and seed phrase ,
if i entered the leave the two field empty or one of two and click recover button (submit button) give me the error in the seed phrase and I think it must check if the data is empty or not in the first before making the request  and give me error to tell me that there is a empty data .

https://github.com/threefoldtech/test_feedback/assets/101194226/6edaee1c-6a4d-4f81-aa1e-f69c4e071f78

### What did you expect?

I expect error to tell me that there is a empty data .

### Relevant log output

Threefold Connect Version: `3.7.3 - 173`

![image](https://github.com/threefoldtech/test_feedback/assets/101194226/2cbd4056-a6af-42a5-a873-96c54d87e790)

**Comment by AhmedHanafy725** [comment]
duplicate #542
