### ISSUE TITLE
[Bug 🐞]: Threefold Connect: Confirm seed Phrase in Sign up.

### ISSUE THREAD

**Issue by aliwaleed1** [threefoldtech/threefold_connect#549]
### What happened?

when the app ask you to Confirm seed Phrase ,you must Type 3 random words from your seed phrase but if  type same word three time the app accepts and goes to next step.

https://github.com/threefoldtech/test_feedback/assets/101194226/72a3e083-3403-4942-87d1-d0bf8108e78f

### What did you expect?

the app must not accept same word three time if the word already exists in the user seed Phrases ,and show error message to type three different words in seed Phrases.

### Relevant log output

Threefold Connect Version: `3.7.3 - 173`

![image](https://github.com/threefoldtech/test_feedback/assets/101194226/2cbd4056-a6af-42a5-a873-96c54d87e790)

**Comment by AlaaElattar** [comment]
### Work Completed:
- added condition to check that entered words won't have any duplicates, they should be distinct.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The issue has been fixed, currently the App doesn't accept the same word  3 times to confirm the seed phrase, and error message is displayed.


https://github.com/user-attachments/assets/e00b2d41-cfc9-4acd-a9e5-77acc85c1ef8


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407469#case_4049038
