### ISSUE TITLE
Can't connect to the Planetary Network 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/threefold_connect#552]
IOS, app version 3.7.3 - 172.

Can't connect to the Planetary Network, given me the error to accept VPN permission first but there's not any permission asked. 

And also couldn't find any docs in https://manual.grid.tf/getstarted/TF_Connect/TF_Connect.html about how to activate Planetary Network or what does it do.

![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/8b827343-fe6a-4bf7-b2a0-1ca68b17ec3c)

**Comment by AhmedHanafy725** [comment]
planetary network is removed from the app #568
