### ISSUE TITLE
Typing in the support page causes the UI to fail.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/threefold_connect#553]
IOS, app version 3.7.3 - 172.

1. When I try typing in the chat support, it sometimes loads like below. (I am only sending a message so the chat should be visible not the loading). 

a. In chat
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/8f1b4a26-4677-4871-88c8-a1c04a8da752)

b. In help desk.
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/ea9bdbe3-c5ba-4dad-9f81-b05b22817752)

2. When I finish typing, it show white space as below from keyboard and it doesn't go away.

a. In chat.
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/1636a048-5e75-46a5-a36b-040192222294)

b. In help desk.
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/85d713cb-6029-4429-9ed1-68e858e496fc)

**Comment by zaelgohary** [comment]
Works normally.

![image](https://github.com/user-attachments/assets/0cad5538-2dad-4483-85fc-8408a8250666)

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Typing in the support page input works fine and does not cause UI to fail.

![chat](https://github.com/user-attachments/assets/9f27d86e-11ee-494a-8cb5-663387a9fca0)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407475#case_4045876
