### ISSUE TITLE
Searching in helpdesk isn't working correctly

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/threefold_connect#554]
IOS, app version 3.7.3 - 172.

When you try to search for anything in the helpdesk in the support page, it shows u another question or nothing. 
and page freezes at the end, you can't click anything only option is to go back or change page from menu.

https://github.com/threefoldtech/threefold_connect/assets/109473873/ff18144d-66af-4ed3-b0c9-2eb2ac0da8f6

**Comment by zaelgohary** [comment]
Works normally.

![image](https://github.com/user-attachments/assets/c7450485-91e5-436e-ae2c-1c7dc3d1f76b)

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Help desk searching works as expected.


https://github.com/user-attachments/assets/658ac428-45ae-42ea-a4fe-836433ad601e


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407475#case_4045878
