### ISSUE TITLE
Cleanup tags

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/threefold_connect#565]
This repo has a lot of tags that don't make sense. After v3.6.0 there's over 60 tags with v0.x.x, v1.x.x, and v2.x.x.

**Comment by scottyeager** [comment]
Hi @AhmedHanafy725,

I guess you closed this issue by mistake, because the problem still exists and I don't see any explanation of why we shouldn't address this.

Some tags are even duplicates that point to dangling commits that aren't found on any branch. Check [here](https://github.com/threefoldtech/threefold_connect/commit/716602463dde9f3399029d6aaaed741fe7580503) for example:

![image](https://github.com/threefoldtech/threefold_connect/assets/17682591/1d5d5602-1415-4000-8ceb-dd3eda55f70d)


We're also missing any legitimate tags (and releases) after v3.6.0, even though new versions are clearly being pushed out to the app stores.

**Comment by xmonader** [comment]
@scottyeager I didn't get at the start, I don't find the newest tags as well. 

@AhmedHanafy725 please double check that

**Comment by AhmedHanafy725** [comment]
Work Completed:

All useless tags got removed. Also, added a new tag for the latest release.
