### ISSUE TITLE
Change transaction color type and add status

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/threefold_connect#566]
The transaction color of red and green (sent and received) isn't clear for the user, especially since the red means receive, not fail!
And also, there isn't any way to tell if a transaction was successful or not; no status appears anywhere in the app.
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/34fc5a95-f1bd-46c7-89f0-8ee7f6e176e8)

**Comment by ehab-hassan** [comment]
Working in Progress 
ll update Figma Soon

**Comment by ehab-hassan** [comment]
the default must be Green for receive and Red for send also we add ( - ) at send to be clear for the user 
also, we can add the status of the transaction at the right of 
@AhmedHanafy725 what do u think?

![Wallets](https://github.com/threefoldtech/threefold_connect/assets/10484295/1c1ad0b7-698e-473f-a5be-96745dabbe2f)

**Comment by khaledyoussef24** [comment]
blocked on https://github.com/threefoldtech/threefold_connect/issues/667

**Comment by khaledyoussef24** [comment]
verified on 3.9.1
Android 15

now transactions colors are looking so much better and descreptive.

![Image](https://github.com/user-attachments/assets/4a22ae9a-3761-4ac2-a054-4b870e13ae8d)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4046920)
