### ISSUE TITLE
Change link to privacy policy on appstore 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#567]
Apple
Pls change link to developers privacy policy https://library.threefold.me/info/legal/#/legal__privacypolicy

**Comment by AhmedHanafy725** [comment]
I have updated the privacy policy link but it will take some time to reflect

**Comment by sabrinasadik** [comment]
Not reflecting yet

**Comment by AhmedHanafy725** [comment]
> Not reflecting yet

yes, still under review from the app store side. I'll keep the issue updated once they finish

**Comment by AhmedHanafy725** [comment]
available now on the app store
