### ISSUE TITLE
Remove planetary network from app 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/threefold_connect#568]

**Comment by AhmedHanafy725** [comment]
as the first step, we will migrate flagsmith server to our own instance

**Comment by sabrinasadik** [comment]
My bad, I meant Planetary network. Apologies!

**Comment by AhmedHanafy725** [comment]
1. Work Completed:
- The planetary network has been removed from the code.
- Did a local test against android

The ios version needs to be tested too

**Comment by ramezsaeed** [comment]
Work in Progress (WIP):
- Android test results can be found here: https://app.testlodge.com/a/26076/projects/40893/runs/725092


![Screenshot from 2023-12-01 18-15-55](https://github.com/threefoldtech/threefold_connect/assets/16083592/ff90f2d5-64f5-41d3-a20e-a60dc500214b)

**Comment by AhmedHanafy725** [comment]
Work Completed:
the iOS version is also available as a test flight now. I'll release them to be reviewed in the stores once the internal testing is done.
