### ISSUE TITLE
fix error message when recover account with empty name and correct seed

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/threefold_connect#575]
Description
- try to test the message of required fields

Test steps

1. leave the name empty
2. write the correct seed
3. click on recover button

Expected results
- must give me that the field is empty

![Screenshot from 2023-12-01 14-52-55](https://github.com/threefoldtech/threefold_connect/assets/16083592/947bd7d8-bb2f-4265-a12a-792e3ff96e06)

Test Environment:
TFconnect version: 3.9.0-176
Android version: 12
kernel version: 4.14.113-25741823

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The error message has been changed to "Name is required"
![image](https://github.com/user-attachments/assets/6e948ba3-a6b4-4ace-ab9f-310d61320d29)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407470#case_4050848
