### ISSUE TITLE
 the app can't open a news article from the News page and display its content.

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/threefold_connect#576]
Test steps
1.Open the application.
2.Click on menu icon.
3.Click on "News" in menu items.
4.Click on a news article to open it

Expected results
News article is displayed correctly with the title, reading minutes , date, and body content.
Should be a News button to navigate you back.

current status:
keep do nothing when click on an article

Test Environment:
TFconnect version: 3.9.0-176
Android version: 12
kernel version: 4.14.113-25741823

**Comment by zaelgohary** [comment]
Couldn't reproduce. All articles redirect to news details. 

![image](https://github.com/user-attachments/assets/0ff0c9c5-86ca-4cd2-9c4c-6376850737d9)

![image](https://github.com/user-attachments/assets/aef89745-7fe5-4b32-bbb6-158b7f470ee0)

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- All articles redirect to news details by click on "Read More"


https://github.com/user-attachments/assets/a76cc59b-7a67-4826-8c20-71bfe11c60d9


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407472#case_4048994
