### ISSUE TITLE
Send/ Receive Tokens via TFChain hangs with no timeout

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/threefold_connect#577]
Test steps
1.Open the application.
2.Click on menu icon.
3.Click on "Wallet" in menu items.
4.Write your PIN code.
5.Click on "Receive Coins"
6.Select "TFChain" as Chain.
7.Enter a positive number in amount .
8.Select asset in the "Asset" combo box.
9.Click on "GENERATE QR CODE".

Expected results
1.QR code is generated successfully and contains all the transaction details.
2.the coins for this Chain increase by the amount.

Current status:
sending tokens hangs for ever and doesn't timeout or give any error.

Test Environment:
TFconnect version: 3.9.0-176
Android version: 12
kernel version: 4.14.113-25741823

**Comment by khaledyoussef24** [comment]
verifed on 3.9.1
version android 15

made transactions throught qr codes and did not face the same error and worked smoothly

![Image](https://github.com/user-attachments/assets/850d5b2a-49fa-4d76-bf4f-278ec1867cf0)
![Image](https://github.com/user-attachments/assets/832e7789-b41d-4a8d-b315-a372b3c86e01)
![Image](https://github.com/user-attachments/assets/3c2a22ab-b235-4122-9d47-8d1acb1ca754)



[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4046943)

**Comment by ramezsaeed** [comment]
@khaledyoussef24 
TFchain word looks very wired here
please check again in the latest version.
