### ISSUE TITLE
confusing popup error message while sending coins

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/threefold_connect#578]
when try to send coins
directly after scan the receiver QR code.
popup message appears down the screen indicates there is no wallet with enough TFTs; how ever the process continue after that and send coins succeeds.

![Screenshot from 2023-12-01 16-38-09](https://github.com/threefoldtech/threefold_connect/assets/16083592/f520ed07-dedc-4c96-9890-491d2de45dde)

Test Environment:
TFconnect version: 3.9.0-176
Android version: 12
kernel version: 4.14.113-25741823

**Comment by khaledyoussef24** [comment]
verifed on 3.9.1
version android 15

made transactions and did not face the same error

![Image](https://github.com/user-attachments/assets/5a10daf3-fef9-4983-b852-c24e941472a6)
![Image](https://github.com/user-attachments/assets/2e5682c7-b999-49fb-8f4c-65d8fbb21e35)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4048983)
