### ISSUE TITLE
Unable to Record a voice message in TFconnect app

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/threefold_connect#581]
Test Environment:
TFconnect version: 3.9.0-176
Android version: 12
kernel version: 4.14.113-25741823

Description
Cannot Record a voice message containing the user problem or question.
however I had enabled the mic permission in the app settings.

Test steps
1.Open the application.
2.Click on menu icon.
3.Click on "Support" in menu items.
4.Record a voice message and send it to the support team.
5.Verify that the support team receives the voice message.

Expected results
1.The user should be able to send a voice message to the support team through the app.
2.The support team should receive the voice message and provide a response.

![Screenshot from 2023-12-01 17-44-33](https://github.com/threefoldtech/threefold_connect/assets/16083592/ee7ae487-be50-477c-949a-70d096d7451b)

**Comment by zaelgohary** [comment]
Audio is not enabled in chat.

![image](https://github.com/user-attachments/assets/621d971e-fbca-4c37-87a7-6d5349abf8e0)

**Comment by atefnazmy** [comment]
- The audio recording is not supported.
