### ISSUE TITLE
Failed Send an email to the support team through the app.

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/threefold_connect#582]
Description
Send an email to the support team through the app , and get response for the question.

Test steps
1.Open the application.
2.Click on menu icon.
3.Click on "Support" in menu items button.
4.Click on "ThreeFold Network" then click "Continue on Email".
5.Enter a subject and message in the email and send it.
6.Verify that the support team receives the email .

Expected results
1.The user should be able to send an email to the support team through the app.
2.The support team should receive the email and provide a response.

current status:
- when click the email icon it redirect to "web page not available".
- Also i had to force close the app and restart it again so I can show the support page after the email fail.

![Screenshot from 2023-12-03 15-24-13](https://github.com/threefoldtech/threefold_connect/assets/16083592/0aad7002-e64c-417c-9919-9ed95737d0f2)

### Note:
its also better if we are directly able to send email without get into the chat itself.
as currently so I can see the email icon i had send first message first.

Test Environment:
  TFconnect version: 3.9.0-176
  Android version: 12
  kernel version: 4.14.113-25741823

**Comment by zaelgohary** [comment]
I followed the steps and was redirected to a compose mail page as seen below.

![image](https://github.com/user-attachments/assets/6d83f13f-a253-444a-9521-f86404a5b340)


then the chat was updated with the mail subject & body.

![image](https://github.com/user-attachments/assets/dafc2fdb-cc9b-48fd-acbc-a683640d1e1c)

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Sending Email to the support team works as expected.


https://github.com/user-attachments/assets/6f338c58-d5d8-4dc7-9679-1a57d091a4f4


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407475#case_4045914
