### ISSUE TITLE
Attach file in support chat force close the app

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/threefold_connect#583]
Test Environment:
TFconnect version: 3.9.0-176
Android version: 12
kernel version: 4.14.113-25741823

**Comment by zaelgohary** [comment]
I could attach a file normally.

![image](https://github.com/user-attachments/assets/ca4be76e-59f9-45a5-af2c-580234be4798)

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Attaching file in support chat works as expected with no error

https://github.com/user-attachments/assets/06411529-5a59-414f-9cc9-4d6bd904a4b0

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407475#case_4045915
