### ISSUE TITLE
Revisit the app UI

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#586]
here are some issues for having better UI. Please add your suggestions too.

- #561 
- #536

**Comment by khaledyoussef24** [comment]
the 2 related issues are verified
![Image](https://github.com/user-attachments/assets/82cf81f1-4d57-46ba-9fff-2df172a8d962)
![Image](https://github.com/user-attachments/assets/80dfc531-b3b9-478e-8506-d3bb0769e10e)
UI enhanced now in home and pin screen
