### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#587]

**Comment by khaledyoussef24** [comment]
dark mode is now supported in the app
![Image](https://github.com/user-attachments/assets/40500723-34a2-4199-a802-a807f0f21711)
![Image](https://github.com/user-attachments/assets/e14d7c71-0fd2-4ee3-8f21-a9ee99b7d053)
![Image](https://github.com/user-attachments/assets/da17b303-ee19-474a-8f06-a62ce1c2020b)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407478#case_4404609)
