### ISSUE TITLE
Use the same colors as the new dashboard 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#588]
dashboard.dev.grid.tf

**Comment by khaledyoussef24** [comment]
verified 
version 3.9.1

dark mode dashboard : 
![Image](https://github.com/user-attachments/assets/ab394665-12dd-4b63-be33-0c1302ee8865)
dasrk mode tf connect:
![Image](https://github.com/user-attachments/assets/fff26a03-0333-4e31-9e13-6775e93fccd9)

light mode dashboard :
![Image](https://github.com/user-attachments/assets/9b3000d7-a2d0-48fd-bc1a-c8889c2e32b2)
lightmode tf connect
![Image](https://github.com/user-attachments/assets/cc96554e-4b49-4740-a955-3766999ee602)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407478#case_4404609)
