### ISSUE TITLE
Add the wizard to the app

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#589]
the wizard is now served on a separate website. It should be on the app itself.

**Comment by khaledyoussef24** [comment]
verified now screens are built in the app 
only the copyrights and terms are on a website
![Image](https://github.com/user-attachments/assets/29bf5d7d-23a9-4381-b509-7cca91b68349)
![Image](https://github.com/user-attachments/assets/293830e1-bbeb-4862-bceb-bbb146d5d9af)
![Image](https://github.com/user-attachments/assets/8b77e77c-b6f2-4a65-b4de-0ddccab9196f)
![Image](https://github.com/user-attachments/assets/1f6f655a-f60d-4ea7-b4ce-fa447cee0821)
![Image](https://github.com/user-attachments/assets/84946b86-32b8-4c29-b614-57de4f703a7e)
the copyrights:
![Image](https://github.com/user-attachments/assets/e8250710-a499-4145-9bdc-87827268ccb2)

**Comment by khaledyoussef24** [comment]
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407468#case_4409420)
