### ISSUE TITLE
Add DAO vote functionality

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/threefold_connect#593]
![Screenshot 2024-03-06 at 10 08 25](https://github.com/threefoldtech/threefold_connect/assets/50134479/581fd106-1890-4a6c-9f84-3fa9a8e2ac08)

This is a good point from Robert, it would be much easier for people to vote on mobile.

**Comment by khaledyoussef24** [comment]
version 3.9.1
APK30-10-2024
Android version 15

DAO Voting is now functionality 

steps to verify: 

1. Go to polka dot
2. Create a proposal
3. Go to Threefold connect app
4. Add your wallet
5. Go to DAO
6. choose the proposal you want to particpate in
7. choose your farm
8. vote with yes or no
9. The vote shall be reflected
 
![Image](https://github.com/user-attachments/assets/801c448b-b3bc-418e-a038-5349ea282f53)
![Image](https://github.com/user-attachments/assets/6f2a6976-0e53-43bf-acdf-5ef165e344ba)
![Image](https://github.com/user-attachments/assets/0a693087-7c48-470e-b9cd-6da60459723c)
![Image](https://github.com/user-attachments/assets/3a9e2764-534e-4c7f-b218-00543220d832)
![Image](https://github.com/user-attachments/assets/cbb105a4-5c79-43c8-9e68-e408aace0a6c)
![Image](https://github.com/user-attachments/assets/db91c7b4-4953-456e-9ae0-4cf1d9ce3bad)



[testcases](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=454829#case_4409437)
