### ISSUE TITLE
Issue with the TF Connect App for multiple users 

### ISSUE THREAD

**Issue by Cameron1986labeyrie** [threefoldtech/threefold_connect#594]
Farms are not showing up.

![img3185_1yq8vpx (1)](https://github.com/threefoldtech/threefold_connect/assets/152964575/b473b04d-b684-486d-a400-cd2a125e2e7c)

https://github.com/threefoldtech/threefold_connect/assets/152964575/3561a809-90d6-4c73-b138-5013c4ccf3c1

**Comment by AhmedHanafy725** [comment]
The issue is addressed and solved. Can you please try it?

**Comment by Cameron1986labeyrie** [comment]
Hello @AhmedHanafy725 , I checked the App and yes, the farms seem to be showing up, Thank you!
