### ISSUE TITLE
KYC verification

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#595]
the current KYC verification flow is done in 3 steps:
- Email verification (enabled by default for all users) using SMTP
- Phone verification (can be enabled for certain users) using [Twilio](https://www.twilio.com/en-us)
- Identity verification (can be enabled for certain users) using [Shufti Pro](https://shuftipro.com/)

### Identity Verification
- It scans the national ID, passport, or driving license and takes a selfie photo for the user.
- Can be done only if the phone number is verified.
- There is a configurable rate limit for the user to try the verification per day.
- [Pricing](https://shuftipro.com/press-release/prices-for-shufti-pros-digital-identity-verification-service-positively-stir-the-public/)
- Can check from the dashboard how many verifications are done, who tried to verify, and the verification score

![image](https://github.com/threefoldtech/threefold_connect/assets/41957921/0e29645b-5a19-4719-819b-e77a0aa325eb)

**Accepted**
![image](https://github.com/threefoldtech/threefold_connect/assets/41957921/f50ba3ce-0f46-4eb1-90aa-4ff00a659bcb)

**Declined**
![image](https://github.com/threefoldtech/threefold_connect/assets/41957921/9e711f59-8389-4899-b1dc-c6616a742bf2)

**Comment by despiegk** [comment]
for me good to go for this, then civic not needed
