### ISSUE TITLE
Test run progress for ThreeFold Connect

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#602]
### Progress on running test for the newly released threefold connect app

- [x] [Tf connect IOS](https://app.testlodge.com/a/26076/projects/40893/runs/744272) V3.9.1
- [x] [Tf connect Android](https://app.testlodge.com/a/26076/projects/40893/runs/744279?tab=0) V3.9.1

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/threefold_connect/issues/603

**Comment by khaledyoussef24** [comment]
#604
