### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#604]
IOS V3.9.1

Some of the components of the UI needs improvement:
![image](https://github.com/threefoldtech/threefold_connect/assets/110984055/433c294c-6c6a-4589-a0e4-52649cdd66a1)
The 2 fields are expanded while arrows looking inverted( the tfchain expand arrow is inverted)
![image](https://github.com/threefoldtech/threefold_connect/assets/110984055/e9908fe1-33e6-4987-b784-e68879a198a0)
The farmer version is written in unclear location.

**Comment by khaledyoussef24** [comment]
version is now found in settings only
![Image](https://github.com/user-attachments/assets/b3680d33-0a33-423a-8483-f3cd6afb71d1)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407478#case_4050875)

**Comment by xmonader** [comment]
For the version: There're no separate versions for webviews, there're no more webviews. the only version that exists now is the app version in the settings page.

For the rest to be reverified.

**Comment by khaledyoussef24** [comment]
version 3.9.1
the new version has enhanced ui for the farms section
in both light and dark mode : 
![Image](https://github.com/user-attachments/assets/20dd2100-4508-4455-8384-1053ce74e30a)
![Image](https://github.com/user-attachments/assets/12ae7904-9b0e-4c94-8b1e-e6687235293b)
![Image](https://github.com/user-attachments/assets/04d5a0d0-26bf-400e-a5c7-6156252d0b88)
![Image](https://github.com/user-attachments/assets/9b02b2ab-ee41-439b-ad6e-4b7ff5acf1c4)
[test case](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407474#case_4050861)
