### ISSUE TITLE
Error message enhancement while adding a wallet address

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#605]
Faced this error searching for a previous added wallet:
![image](https://github.com/threefoldtech/threefold_connect/assets/110984055/a65c9ee2-1b70-4d7a-bc9e-5c68492b2dc5)![image](https://github.com/threefoldtech/threefold_connect/assets/110984055/6ef40b07-963b-47e8-8cbf-d50cc59f6544)

Can we improve the error message to mention if the contact address is already added stellar or tfchain so users can find contacts easily?

**Comment by zaelgohary** [comment]
Still investigating.

**Comment by zaelgohary** [comment]
Work completed:

Added chain type to err msg when the user tries to add an existing contact.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The Enhancement has been done, and an error message mentions if the contact address is already added in Stellar or TFChain.


![image](https://github.com/user-attachments/assets/7efd2ff4-7251-4e8a-aa38-a4f2e8da6878)


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4404602
