### ISSUE TITLE
Not all the wallet shown in create farm

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/threefold_connect#606]
So these are my wallets; `harbya` is the main one created by ThreefoldApp, and `mainnetharby` and `test` are the ones I imported.
First, when I try to create a farm, only 2 wallets are shown, not three.
Secondly, the farms listed here are from different wallets (I can't differentiate between which is owned by which).

![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/a948c551-3f94-479d-8c9d-fc53272ce056)
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/b5c686c2-7ca8-436e-97bb-bb1ddb547e97)
![image](https://github.com/threefoldtech/threefold_connect/assets/109473873/1fb9e173-9b6e-4738-9315-b21779fb28e2)

**Comment by khaledyoussef24** [comment]
verified version 3.9.1
added more than 5 wallets
user can now scroll while creating a farm to see the wallet he wants![Image](https://github.com/user-attachments/assets/876e4e54-ca74-464f-91ec-ec5718944d40)
![Image](https://github.com/user-attachments/assets/156bdf34-dc2d-43d4-852a-c4e7f97ae1e7)
![Image](https://github.com/user-attachments/assets/c2bba50f-096d-40a5-8625-d6d0e751f884)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4407754)
