### ISSUE TITLE
Change images at Wizard Pages to match the new theme

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/threefold_connect#617]
Change images at Wizard Pages to match the new theme
https://github.com/user-attachments/assets/127288e3-0393-4299-9fd3-ffcb3d8eb8a7

**Comment by ehab-hassan** [comment]
outline
![Frame 427320955](https://github.com/user-attachments/assets/95e4efa1-bcbd-493f-bed8-b7cd3d88c2b0)

solid
![Frame 427320956](https://github.com/user-attachments/assets/9c114b64-f712-4f8e-98ac-62234e58accc)

outline_light mode

![Frame 427320957 (1)](https://github.com/user-attachments/assets/674333a1-5c65-464e-bf0e-c939ac9388bb)

**Comment by ehab-hassan** [comment]
source images
![
![Uploading rocket_outline.png…](
![wallet](https://github.com/user-attachments/assets/ffbde74c-e0e0-4269-a5a6-42144e2c844c)
)
wallet_outline](https://github.com/user-attachments/assets/40bbdcd1-2e8d-406e-8335-4f37619bc3a4)
![finger](https://github.com/user-attachments/assets/b13e1cda-f8a2-4c0f-a94b-8377cbf06790)
![finger_outline](https://github.com/user-attachments/assets/517ac0ae-14e7-4b46-a687-a718e753b82a)
![news](https://github.com/user-attachments/assets/72232981-6e97-4009-9606-f0846eb17d23)
![news_wallet](https://github.com/user-attachments/assets/49300485-18de-4922-99b3-a6bb1550cbc9)
![rocket](https://github.com/user-attachments/assets/4e752560-45de-4860-b8a9-910f93eb0919)

**Comment by ehab-hassan** [comment]
- can we make all title smaller by 30% and all wizard images smaller by 20% like the guide
![photo_2024-10-13_11-04-30](https://github.com/user-attachments/assets/39e94dfe-7850-4dac-8812-97f09cc25719)



- also at the start threefold journey can we make it consistent like other pages' title then image.
- 
![photo_٢٠٢٤-١٠-١٣_١٠-٥٨-٣٦](https://github.com/user-attachments/assets/4fa70114-75f6-48cd-84cb-480f096c95ac)

- also I think it is enough to say "Start your journey" @AhmedHanafy725 what do you think?
![image](https://github.com/user-attachments/assets/d2e5c454-f797-47dd-a473-df6a1f2527ba)

**Comment by ehab-hassan** [comment]
![news_wallet](https://github.com/user-attachments/assets/cdf14beb-0722-4329-9d6b-4143659f753b)
please use this image for news there is a dark stroke at the old one I removed it to me consistency like other

**Comment by khaledyoussef24** [comment]
verified in the new version 
![Image](https://github.com/user-attachments/assets/803ff33a-7083-4a1a-bed0-f616b641b227)
![Image](https://github.com/user-attachments/assets/8c66e45d-4f45-41be-b6c7-029596336f88)
![Image](https://github.com/user-attachments/assets/a8b8595c-ae42-4f6f-94d3-a6f056c9d72e)
![Image](https://github.com/user-attachments/assets/8b055e92-653e-4d00-b9ef-92be36e40a7d)
![Image](https://github.com/user-attachments/assets/ad7cced7-7f0c-4844-bcc0-62c3b2d48ac7)
