### ISSUE TITLE
introduce KYC with idenfy in the mobile app

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#624]
child of https://github.com/threefoldtech/home/issues/1572

**Comment by AhmedHanafy725** [comment]
### Work In Progress

I made the most changes, but now waiting for the service to be ready to test the flow and handle the edge cases.

**Comment by AhmedHanafy725** [comment]
### Work In Progress

The integration is done. I am waiting to confirm the status code on the service and encode the date of birth.

**Comment by khaledyoussef24** [comment]
Verified 
IOS 18
version 4.0.0
 
Idenfy is now updated KYC is added to it 
User shall add his phone number
then start the verification process
![Image](https://github.com/user-attachments/assets/4d312b6d-9150-450e-bb16-e0159fff9ffb)
![Image](https://github.com/user-attachments/assets/5c2a73c5-3899-433f-a361-a84bbc45ab3a)
![Image](https://github.com/user-attachments/assets/5f2ba2cf-fb20-4ac1-8c92-96d6873f4a5e)
![Image](https://github.com/user-attachments/assets/80ce838a-2220-472a-b67e-00066e41dcd3)
![Image](https://github.com/user-attachments/assets/770f9a25-65d6-4d2c-9cdf-651c08816d1f)
![Image](https://github.com/user-attachments/assets/b0afe3c3-87cf-420c-b556-ffd4cad2d16a)
![Image](https://github.com/user-attachments/assets/3969362b-a329-4366-b5a6-55de22e64198)
![Image](https://github.com/user-attachments/assets/115b04e2-bb52-41e1-b3db-2b4ce9ad4e27)
![Image](https://github.com/user-attachments/assets/02b1b25a-db6a-4ae1-9ed4-dbe0991042be)


then User can verify KYC
if user didnot have 100 tft in any wallet ![Image](https://github.com/user-attachments/assets/9384722d-fae0-4e65-9619-3271385330be)

if user have 100 tft
![Image](https://github.com/user-attachments/assets/2c3f20c5-eca3-4bfd-8a3b-d2d61e2725d8)
![Image](https://github.com/user-attachments/assets/4379a259-2028-4c06-885a-1dcf65a8a3b3)
![Image](https://github.com/user-attachments/assets/083ea838-ff16-4a4c-aea6-63c03d183bbf)
![Image](https://github.com/user-attachments/assets/5bc4f4d5-d997-459c-9296-4e53b2a8c6bc)
![Image](https://github.com/user-attachments/assets/ea6cf6f4-e7c4-4878-8d81-8877c1be6e41)
![Image](https://github.com/user-attachments/assets/b576c489-7665-4838-aa1e-d727ff7f3195)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407477#case_4412672)
