### ISSUE TITLE
Error when navigating to wallets and farms without first wallet created

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#629]
Description: When navigating to the wallets and farms section without having created a wallet, an error message is shown saying, "something went wrong." The message could be improved for clarity.

Expected Behavior: If no wallet has been created, the user should see a message prompting them to "Create your first wallet" instead of an error.

Steps to Reproduce:

Go to the wallets and farms section without creating a wallet.
Observe the error message "something went wrong."
Proposed Solution: Replace the error message with a more user-friendly prompt to "Create your first wallet."

the failed to load the message in the both footers and in the middle of the wallet page
![image](https://github.com/user-attachments/assets/6a649190-aa64-4fdc-92e0-3b16f51d0a9a)
![image](https://github.com/user-attachments/assets/26a30bd1-7299-483f-9f46-6d0c4b8013ca)

**Comment by khaledyoussef24** [comment]
issue is no longer reproducable
![Image](https://github.com/user-attachments/assets/406fabfc-485e-46bf-a986-7c35b737b43a)
![Image](https://github.com/user-attachments/assets/405da5bd-fab2-4b12-a24d-1ea1ab2bc8e6)
![Image](https://github.com/user-attachments/assets/afe69b1f-cf07-46e6-8627-4fd092f806a0)

**Comment by ramezsaeed** [comment]
@khaledyoussef24 
where is the test case link ?
