### ISSUE TITLE
User can set PIN to the same value again

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#630]
### Description:
 The system allows users to change their PIN to the same value that is already set. While this is functional, it may not provide a strong user experience.

### Expected Behavior:
 The system should notify the user if they are trying to set the same PIN again and encourage them to choose a different value for better security.

Steps to Reproduce:

1. Set a PIN (e.g., "1234").
2. Attempt to change the PIN to the same value ("1234").
3. Notice that no warning or validation prevents this.
4. Proposed Solution: Add validation to prompt the user when they attempt to reuse the same PIN.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Cannot set same value when changing the Pin, and a message with "New pin must not match the old one" appears

https://github.com/user-attachments/assets/626ba23b-8fe7-4891-88dd-f0d766f758bb

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407478#case_4050872
