### ISSUE TITLE
Enhance settings by showing user information

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#631]
### **Description:** 
Currently, clicking on the username in the settings does not display any user details. This could be enhanced by showing the user’s information, such as their email address.

### **Expected Behavior:** 
Clicking on the username in settings should display user information, including their email and other relevant details.

Steps to Reproduce:

1. Go to settings.
2. Click on the username.
3. Notice that no additional user information is displayed.
4. Proposed Solution: Enhance the UI to display the user's email and other relevant information when their username is clicked.

**Comment by zaelgohary** [comment]
Name & show phrase should be moved to Identity.

**Comment by AlaaElattar** [comment]
### Work Completed :
- Updated the page with the new design requested by @ehab-hassan.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The enhancement has been implemented by relocating "The User" and  "Show phrase" under "Identity". 

![image](https://github.com/user-attachments/assets/3d003103-4768-418a-b85b-ad9014cbbf3f)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407477#case_4427223
