### ISSUE TITLE
Testing threefold connect new app

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#634]
### **Description:** 

This issue is created to track the progress of testing the new Threefold Connect app.

issues found till now.
#633 
#632 
#631 
#630 
#629

**Comment by khaledyoussef24** [comment]
tested the IOS version on a test flight, and it is working fine

**Comment by ramezsaeed** [comment]
- [Khaled's testrun tfconnect](https://app.testlodge.com/a/26076/projects/40893/runs/762408)

- [Atef TFconnect-3.9.1_Android-14 rc2](https://app.testlodge.com/a/26076/projects/40893/runs/762389)

- [Atef TFconnect-3.9.1_Android-14 rc1](https://app.testlodge.com/a/26076/projects/40893/runs/762081)

**Comment by ramezsaeed** [comment]
Tested the latest APK version dated 30-10-2025 on Android
