### ISSUE TITLE
Failed to initialize wallet

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#635]
### Steps to reproduce
- Go to connect app and login
- go to wallets and try to initialize a wallet

![image](https://github.com/user-attachments/assets/bcfdb623-5e39-4b4e-a334-5e96fa51b3c5)

I don't know if this happens because I have a wallet with the same name or not, but either way, we need to show more info in the error message.

**Comment by Julietnacy** [comment]
@zaelgohary  Sometimes, reinstalling the wallet app can resolve initialization issues.If your app has an option to clear cache or reset settings, try that.

**Comment by khaledyoussef24** [comment]
verified no longer reproducable
could intialize my wallet easily
![Image](https://github.com/user-attachments/assets/001f8ab6-d559-4f3e-8219-574a3738ce45)
![Image](https://github.com/user-attachments/assets/27055c71-2cc4-45bd-a225-e7139436bda3)
![Image](https://github.com/user-attachments/assets/6133726f-3bf1-4e2f-976d-6855f3be5a65)

**Comment by ramezsaeed** [comment]
@khaledyoussef24 
where is the test case link ?
