### ISSUE TITLE
Remove margins from active tab

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#636]
![image](https://github.com/user-attachments/assets/1bc844aa-5d3c-4a01-b740-15b4b8510164)

The active tab has unnecessary space and it looks weird, maybe we can set an active class that will set the logo and tab title to be colored instead?

**Comment by khaledyoussef24** [comment]
version 3.9.1
verified now active tab the icon looks more colorful only

![Image](https://github.com/user-attachments/assets/ccf8baef-19cf-4e45-bd11-330856bf044c)
![Image](https://github.com/user-attachments/assets/a03e4224-a964-4c4c-b95d-be286dd9415e)
![Image](https://github.com/user-attachments/assets/bf0c1a0f-b9b5-41b1-97da-f8c1c40e9c86)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407471#case_4407755)
