### ISSUE TITLE
Enabled DAO buttons when user has no farms

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#637]
![image](https://github.com/user-attachments/assets/26bd621f-dba8-4ae7-b88e-54efd0731c5a)

Both buttons should be disabled if list is empty.

**Comment by AlaaElattar** [comment]
### Work Completed:
- when no farms available to user, will show msg that user can't vote.

**Comment by khaledyoussef24** [comment]
Verified 
version 3.9.1
APK version 30-10-2024
android version 15

![Image](https://github.com/user-attachments/assets/131eb0a0-55e2-460d-9dce-3447c5ca3b96)
![Image](https://github.com/user-attachments/assets/1fa66190-0134-4a6b-9259-f210f4cdcc95)
![Image](https://github.com/user-attachments/assets/486fd847-cca7-490c-9877-a104e7fd69a3)




[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=454829#case_4409447)
