### ISSUE TITLE
Farming page loads forever

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#638]
It's been more than 10 mins and the request hasn't timed out yet.

![image](https://github.com/user-attachments/assets/29a8afdd-de4e-4ddd-ab56-0fafe29fa192)

**Comment by zaelgohary** [comment]
Same with DAO

![image](https://github.com/user-attachments/assets/514868e0-1561-457a-ad73-320a2e28abbd)

**Comment by khaledyoussef24** [comment]
could not produce no more
farming page and DAO now works fine
![Image](https://github.com/user-attachments/assets/16fe5035-7cdb-4799-9faa-87fc692676e6)
![Image](https://github.com/user-attachments/assets/92f305b5-c081-4ec0-a02b-511524316df1)
![Image](https://github.com/user-attachments/assets/72244ef1-0165-4c29-8161-111b35101622)
