### ISSUE TITLE
Face ID logo is incorrect

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#639]
![image](https://github.com/user-attachments/assets/49d38e84-1ab7-4287-a9b0-e94d2a184664)

The logo should be changed to sth more suitable

**Comment by khaledyoussef24** [comment]
Still did not changes 
apk 30-10-2024
version 3.9.1
andorid 15
![Image](https://github.com/user-attachments/assets/66ee11e2-0613-4307-aa22-e0017cbf35fa)

**Comment by AlaaElattar** [comment]
### Work Completed:
- Updated condition to handle Face Unlock with android devices.

**Comment by khaledyoussef24** [comment]
still the same on the latest version we may need to check
![Image](https://github.com/user-attachments/assets/0eafd767-cb0a-40f3-b09c-a5d632630c6b)

**Comment by khaledyoussef24** [comment]
verified on IOS
IOS version 18
TFconnect version 4.0.0

![Image](https://github.com/user-attachments/assets/af8c9a0c-d062-4181-9600-6521e8920758)
![Image](https://github.com/user-attachments/assets/29eb4301-7e02-4eaf-ab29-1e41d69dd7d4)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407478#case_4050873)
