### ISSUE TITLE
User should have his wallets listed after login

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#640]
The current flow expects the user to import each wallet if he logs in but a better flow will be that the user finds all wallets linked to his seed listed in the wallets section.

**Comment by khaledyoussef24** [comment]
now all wallets are linked in the wallets sections after you signup and go to wallets

![Image](https://github.com/user-attachments/assets/6f4e3ab6-885f-4c65-be33-007f61e96100)
![Image](https://github.com/user-attachments/assets/5c73ab8b-7e94-4f7a-a81a-9c77265b4386)
if he has no wallets yet : 
![Image](https://github.com/user-attachments/assets/b9185074-4b9e-4d1d-8fbf-30552f071724)


[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4046455)
