### ISSUE TITLE
New App Test: Failing to add new Contact_Stellar add. 

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/threefold_connect#641]
- When attempting to add a contact with the respective Stellar address, the process results with a failure notification: Failed to save contact. Tested this twice with different contacts.

https://github.com/user-attachments/assets/ea5b064b-9581-4f5b-a268-7991b57a1475

**Comment by zaelgohary** [comment]
@TullysInc Can you provide the stellar secrets in a text form? Both secrets are not valid.

![image](https://github.com/user-attachments/assets/cb6bd532-520d-4e55-a086-d39f280fb5f0)

![image](https://github.com/user-attachments/assets/9e96cbfe-725d-4691-bac7-e4f316fb71a5)

**Comment by TullysInc** [comment]
- Amanda
Stellar add: GA4XJAKJDLMGI277VW4AR7KTQVITUWJ6AF6HH545UX2GZ4GLIRPLE67N
Stellar Secret: SBAQR5ULG52AHANCCQY3QPK3EQME5BYO5QOO7UAMD7XWHGPU2T5QDUUT

- Cameron
Stellar add: GC35NS3KDSTGVPLZRQFQPVCOHB4PZQGMSQJWPHKR2NOI4K4RYU24R4UG
Stellar Secret: SC2G6KKROXVRAPKPU5KN76G6O2Q4TQDLAL7EBPK7FXTYSTE35NY6QODX

**Comment by AhmedHanafy725** [comment]
### Work Complete

The issue was loading the contacts when they were empty, and it was required to append the new contact to them.
I also fixed the loading spinner after the failure case.

**Comment by khaledyoussef24** [comment]
verified 
![Image](https://github.com/user-attachments/assets/8dcd116e-267a-45c0-9f78-54126c24fc20)
![Image](https://github.com/user-attachments/assets/d4264447-25b7-4509-abfc-83a8479fd644)
![Image](https://github.com/user-attachments/assets/779b1fa8-9549-440b-9578-91ac6c4d7087)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4404602)
