### ISSUE TITLE
New App Test: Failing to import wallet

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/threefold_connect#642]
- On several test attempts, multiple users are unable to import the wallet using the Mnemonics, Stellar Secret and Hex secret.

https://github.com/user-attachments/assets/26de93c8-88d7-4e76-b1da-a345775f6387

**Comment by zaelgohary** [comment]
@TullysInc Could you please provide the secrets in a text form? I tried the provided mnemonics & it says they're invalid.

![image](https://github.com/user-attachments/assets/29434deb-bd0a-4834-ab11-7c7836f5bff8)

**Comment by TullysInc** [comment]
Sure. Please see below:

- Mnemonics: 
file place repeat voice cage ordinary aerobic what danger argue shift weasel amount during fruit crazy fitness north squirrel enroll issue body cloth infant

- Stellar Secret: SABMTSDWDCOESB3TPBRF23267M77E2X5SBWTUGD2TOZVHD636YGWVHUS

- Hex: 0x02c9c876189c49077378625d6f5efb3ff26afd906d3a187a9bb3538fdbf60d6a

**Comment by AhmedHanafy725** [comment]
### Work Complete

The secrets are correct, but the issue was loading the wallets when they were empty.

<img src=https://github.com/user-attachments/assets/f3e8790e-26e1-4362-ac3d-e41f5c5974e8 width=250>

**Comment by khaledyoussef24** [comment]
verified on the new version

![Image](https://github.com/user-attachments/assets/4f7aba5b-2071-4750-88d9-a74f379fd3e8)
![Image](https://github.com/user-attachments/assets/002f70f5-a3c7-46e9-8709-7a83407cb195)
![Image](https://github.com/user-attachments/assets/6a6ef952-3b49-490c-a8fb-825b25968350)
![Image](https://github.com/user-attachments/assets/388a6240-befa-4131-bd80-21957529d572)
![Image](https://github.com/user-attachments/assets/b6fd0d34-8026-47f5-a011-01f0410e3252)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4046455)
