### ISSUE TITLE
Can't close keyboard in send in wallets

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#644]
### How to reproduce

- Go to wallets then navigate to send
- Enter any field
- Try to close the mobile keyboard by navigating outside the field. It won't get closed.

![image](https://github.com/user-attachments/assets/cb2feb4c-28a8-4b31-85bb-7c9611a333cb)

**Comment by AlaaElattar** [comment]
### Work Completed:
- when user clicks outside the keyboard in the page, it will close.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The keyboard is closed normally by tapping outside the field

![Screenshot From 2024-12-15 22-01-55](https://github.com/user-attachments/assets/fa0256f6-187e-4510-8435-227dd2dd412f)

#### Related Link:
-https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4048983
