### ISSUE TITLE
Persistent amount error in send form

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#645]
I tried to send TFT with an invalid amount and it showed the error below. However, the error didn't disappear once I entered a valid value. Also, I could send while the error was showing.

![image](https://github.com/user-attachments/assets/96667944-c36f-442a-bb9b-46691eca2a59)

**Comment by AlaaElattar** [comment]
- Tried to reproduce the issue multiple times but got nothing, It worked fine and sent 1 TFT.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- It is possible to send 1 TFT without any error.


https://github.com/user-attachments/assets/cd8ad852-2f42-471d-ac4d-e1864e31400a


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4048949
