### ISSUE TITLE
Incorrect email color in dark theme

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#646]
![image](https://github.com/user-attachments/assets/1aecc76b-e041-4a3c-ab4f-fecbb2f9437d)

![image](https://github.com/user-attachments/assets/7c7e3092-c825-41a9-b1df-233f216ae170)

**Comment by khaledyoussef24** [comment]
verified on the new version the change email field is now visible
![Image](https://github.com/user-attachments/assets/6387c0d4-af43-4e6f-8ee2-a44f86400179)
