### ISSUE TITLE
Can't edit my email

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#647]
Whenever I try to change my email, I get this.

![image](https://github.com/user-attachments/assets/be272dd9-e2a7-482f-b39b-c40063a15a64)

**Comment by khaledyoussef24** [comment]
verified on version 4.0.0
IOS version V18

![Image](https://github.com/user-attachments/assets/2e2ca4b5-c90b-43df-92b4-d8c1ca1be257)
![Image](https://github.com/user-attachments/assets/71107a77-a89e-4da1-b942-cff2e3965ba8)
![Image](https://github.com/user-attachments/assets/1c39ed34-eb5a-428a-bc8a-0d22deed9ca1)
![Image](https://github.com/user-attachments/assets/3f118830-a79e-4ecc-9061-2fb631f20c21)
![Image](https://github.com/user-attachments/assets/1a381a18-5152-4837-8280-f44f6e44ecd7)
![Image](https://github.com/user-attachments/assets/adf4bca5-16f2-41da-b6e5-7fc015df97ef)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407477#case_4421009)
