### ISSUE TITLE
Wrong manual link in Support

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#649]
![image](https://github.com/user-attachments/assets/2cce3a93-56f3-48a9-8cbf-985e30d4d885)

### Steps to Reproduce:
- Go to support then click help
- Choose the first question: "How to migrate tokens from Riven...."
- Click the link in the answer

The link should be fixed. Also, page UI is corrupted. Check URL header & farming & settings logo.

**Comment by zaelgohary** [comment]
This is the current UI if the link is valid. The app header is still shown underneath the URL.

![image](https://github.com/user-attachments/assets/b9b9b8d1-cdc1-4204-86b8-9a6dd567655c)

**Comment by TullysInc** [comment]
> * Click the link in the answer

I updated the answer with the correct link. It should be: https://forum.threefold.io/t/migration-from-rivine-to-stellar/3758

**Comment by khaledyoussef24** [comment]
verified works fine now

![Image](https://github.com/user-attachments/assets/abc1d9c7-5418-42e8-8f41-84ba2dcb59fb)
![Image](https://github.com/user-attachments/assets/7c0991d9-00c3-4bb7-856e-72be79d38e41)
![Image](https://github.com/user-attachments/assets/2ad45e5a-4d47-44d6-b357-027a54b4efab)
![Image](https://github.com/user-attachments/assets/a7367cea-074a-4ad5-96f5-274b68d4041d)
[test suite](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407475#suite_section_407475)
