### ISSUE TITLE
Error while listing wallets in new account

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#652]
![image](https://github.com/user-attachments/assets/399c06b0-bab7-4a36-8e82-427018ff44fc)

**Comment by khaledyoussef24** [comment]
verified could list it smoothly now 
and the first message is intialize your first wallet
![Image](https://github.com/user-attachments/assets/e14c321d-a0b8-4e66-bb2b-e810156a343e)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407470#suite_section_407470)
