### ISSUE TITLE
Invisible stepper titles in registration form

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#653]
![image](https://github.com/user-attachments/assets/309282a4-fd99-4f41-88e0-1fad89041221)

Only the first 2 steps' titles are visible in the stepper. Also, remove the dot from the first step.

**Comment by AlaaElattar** [comment]
### Work Completed:
- handle stepper color to be grey if not activated otherwise will be onSurface.

**Comment by khaledyoussef24** [comment]
version 3.9.1
APK 30-10-2024
Android version 15
verified now the stepper titles are in grey

![Image](https://github.com/user-attachments/assets/52da2403-7ab6-40c3-916a-8551a576d74e)
![Image](https://github.com/user-attachments/assets/bbe34913-364f-48c8-a7fb-e77419ea97f9)


[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407469#case_4409430)
