### ISSUE TITLE
Failed to load transactions in wallet

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#667]
after adding a wallet to the app tried to see the old transactions but did not work out and the error at the footer failed to load transactions
![image](https://github.com/user-attachments/assets/b12e7814-a528-40ed-821c-aaccd005a92d)

**Comment by Sarahlouiseryan** [comment]
@khaledyoussef24 What wallet are app is it?

**Comment by AlaaElattar** [comment]
### Work Completed:
- The transactions failed to load as the wallet used in issue doesn't contain stellar activated on it.
- I added check on stellar balance if equals -1, i won't request loading transactions.

**Comment by khaledyoussef24** [comment]
verified it does not request loading in this case and shows no error 
and works smoothly if there is transactions
version 3.9.1
Android 15

![Image](https://github.com/user-attachments/assets/c13b220b-c737-42c2-93fc-86534db9c847)
![Image](https://github.com/user-attachments/assets/6fec8cb9-176c-4dc4-9d27-77eaa6730f4d)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4046920)
