### ISSUE TITLE
loading the amount of money in wallet after choosing a specific wallet takes for ever

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#668]
loading the amount of money in wallet after choosing a specific wallet takes for ever while in the wallet lists it loads fine
![image](https://github.com/user-attachments/assets/242da67f-953a-41aa-aa78-be8df8e4d035)
the wallet list : 
![image](https://github.com/user-attachments/assets/5208fdc5-f232-4281-9bd2-1731b511c2f9)

**Comment by khaledyoussef24** [comment]
after closing the app and opening it worked 
but then after using the app and returning to it was produced again

**Comment by AlaaElattar** [comment]
- I tried to reproduce it many time but each wallet loaded successfully.
- I even tried it with khaled's wallet but still it worked well.
- I guess maybe this was an internet connection error.

**Comment by khaledyoussef24** [comment]
I also faced lots of issues yesterday non of them is reproducible today maybe this also was a connection issue
