### ISSUE TITLE
Wallet disappears after importing it

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#671]
after importing my wallet, I went to the farm's page and then returned to find that the wallet had disappeared
<img width="332" alt="Screenshot 2024-10-23 at 8 54 36 PM" src="https://github.com/user-attachments/assets/3cd9cbbb-8d51-474e-923d-64a493da914f">
<img width="297" alt="Screenshot 2024-10-23 at 8 54 38 PM" src="https://github.com/user-attachments/assets/4e9c0efc-35a6-40f7-ba8c-fac0dcdaf095">
<img width="319" alt="Screenshot 2024-10-23 at 8 55 07 PM" src="https://github.com/user-attachments/assets/4b7159d5-65e6-4010-832a-8c4195437bc7">
<img width="336" alt="Screenshot 2024-10-23 at 8 55 34 PM" src="https://github.com/user-attachments/assets/eb1502c4-73da-43a8-b216-ccf7bd19e4d2">

**Comment by AhmedHanafy725** [comment]
can you record how to reproduce?

**Comment by khaledyoussef24** [comment]
tried to produce the same issue again, but it is not reproducible .
I reproduced it two times yesterday maybe something was not working
will close it for now
