### ISSUE TITLE
User can add the same wallet more than one time

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#673]
The user is able to add the same wallet more than one time in his wallets
![telegram-cloud-photo-size-4-5830095484012840410-y](https://github.com/user-attachments/assets/30ba3f8b-9dbb-41b2-944e-0ee7cb852b67)
(the last 2 wallets)

**Comment by AlaaElattar** [comment]
### Work Completed:
- I added function get hexSeed of secret based on its type.
- I will compare new wallet hexSeed with existing seeds to know if wallet already exists or not.

**Comment by khaledyoussef24** [comment]
verified 
version 3.9.1
APK 30-10-2024
android 15
![Image](https://github.com/user-attachments/assets/4990d4df-181e-4bfc-bf99-81ae8b9a203d)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4409434)
