### ISSUE TITLE
The application logs out after closure, The account and sign-in data are not retained.

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/threefold_connect#680]
### Description:

- After closing and reopening the app, my account and sign-in data are not retained, and the App only shows Signup or Recover account.

### Expected Behavior:
- The app should retain the sign-in session so that users don’t need to Signup or Recover Account  in each time they reopen the app.

### Steps to Reproduce:
 1. Open the app and signup or recover pre-exist account.
 2. Close the app completely (remove it from recent apps).
 3. Reopen the app.
 4. Observe that the app prompts to sign up or recover account again instead of keeping the session active.

https://github.com/user-attachments/assets/b7d26a18-1054-4038-b6a5-05b2cd13cfdb

### Environment:

 • OS Version: Android 14 and 15
 • App Version: 3.9.1

**Comment by khaledyoussef24** [comment]
producable in any device after you close the app from the recently closed menu or the task manager.
