### ISSUE TITLE
Unable to Transfer Amounts with Decimal Values on TF-Chain

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/threefold_connect#681]
### Description:

- Inability to transfer amounts that include decimal values  with  popup message **"Error, Failed to transfer, Please try again"**

### Steps to Reproduce:
 1. Open the app and click on Wallet.
 2. Enter your Pin code.
 3. Select a Wallet, then Click on Send button
 4. Fill in the Receiver field.
 5. Enter an amount that includes a decimal value (e.g., 10.50) and Click on Confirm.

### Expected Behavior:
- The application should allow transactions with decimal values.

### Screenshot of the Issue:

![trans](https://github.com/user-attachments/assets/d5de6136-61bc-4aad-8e00-e8a5de73ac12)

### Environment:

 • OS Version: Android 14 and 15
 • App Version: 3.9.1

**Comment by khaledyoussef24** [comment]
verified 
IOS 18
version 4.0.0

User now can transfer Decimals on tf chain

![Image](https://github.com/user-attachments/assets/ada4942e-d16b-4285-9237-0fb918de5e67)
![Image](https://github.com/user-attachments/assets/00f9866e-b015-4e99-b092-dfc616ad375f)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4046936)
