### ISSUE TITLE
when deleting a wallet, won't appear from wallets page directly.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/threefold_connect#684]
- When deleting a wallet, you have to go to another page then return back to wallets to see it's removed

**Comment by khaledyoussef24** [comment]
I can still produce the same issue is this still pending to deploy ?

**Comment by khaledyoussef24** [comment]
produced one time 
after wallet disappeared it appeared again
https://github.com/user-attachments/assets/6352c4d8-3f97-42f7-96fc-59e5ce4989b5

**Comment by khaledyoussef24** [comment]
@AhmedHanafy725 
could not produce it again 
maybe was the connection speed the issue ?
version 4.0.0
IOS version 18
screencast :
https://github.com/user-attachments/assets/1458cf75-cd1c-4098-8e77-69be12efb79a
