### ISSUE TITLE
Update launcher icon of app

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/threefold_connect#686]

**Comment by khaledyoussef24** [comment]
verified on 3.9.1 
android version 15

the old icon
 ![Image](https://github.com/user-attachments/assets/cd2eafce-481c-4433-88d2-c9af7037ee6c)
the new icon 
![Image](https://github.com/user-attachments/assets/57e58193-52fe-4db7-9d15-440828657ebe)

**Comment by samtaggart** [comment]
Hi there, thanks for changing the color ... Can we make sure the app is ThreeFold Connect, not Threefold Connect? I see in the screenshot above it says "Threefold."

@ramezsaeed tagging you as you are the one who closed.
