### ISSUE TITLE
false Validation message while typing the value in receiving page

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#689]
steps to produce :

1. go to wallet
2. choose a wallet
3. select receive 
4. insert amount 
5. notice the validation message

![telegram-cloud-photo-size-4-5843636974731250474-y](https://github.com/user-attachments/assets/5bc09e71-eb84-411f-b952-4d413d65c64a)

**Comment by ramezsaeed** [comment]
duplicate: https://github.com/threefoldtech/threefold_connect/issues/645
