### ISSUE TITLE
farm page fails to load

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#690]
steps to produce: 

1. insert wallet
2. go to farms
3. notice the error

![telegram-cloud-photo-size-4-5843636974731250476-y](https://github.com/user-attachments/assets/70283805-c5cc-46dd-8e96-e1320ec5928c)

**Comment by Elsiehwoods** [comment]
@khaledyoussef24 Have you tried clearing your browser cache or using a different browser? Sometimes, that can help with pages that fail to load. If that doesn't work, it might be worth checking if there are any updates or known issues with the farm page service you're using.

**Comment by khaledyoussef24** [comment]
worked fine now I double checked may be it was a network issue
![telegram-cloud-photo-size-4-5843636974731250555-y](https://github.com/user-attachments/assets/6f95cdb8-281b-48cb-aeb1-c9f4728630fe)

**Comment by Elsiehwoods** [comment]
@AhmedHanafy725 Okay
