### ISSUE TITLE
UI enhancement : wrong pass code message

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#691]
if the user inserted the confirmation pin wrong the warning may be shown in a better way

![telegram-cloud-photo-size-4-5838960382411131729-y](https://github.com/user-attachments/assets/e021918f-2131-465a-92f5-fdba02e00ba2)

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The "Pin" confirmation message has been updated with enhancements.

 ![Image](https://github.com/user-attachments/assets/28641d2b-cfea-46d2-885b-59f5cbaf8924)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407470#case_4050844
