### ISSUE TITLE
Email and TF ID validation while singing up is not effective 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#697]
steps to produce : 

1. Go to sign up 
2. choose name starting with a number
3. choose an email starting with a number
4. will accept both

![telegram-cloud-photo-size-4-5843636974731250557-y](https://github.com/user-attachments/assets/5c95daa1-271c-41f1-b63c-e3ed5368d179)

**Comment by ramezsaeed** [comment]
will only validate max length for the name.
and there is already a pr for the email validation.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Both User & Email validations work as expected.

https://private-user-images.githubusercontent.com/32517137/398412659-12dda88a-19e3-44a9-9bb1-672b68ea70a1.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDA3NjUsIm5iZiI6MTczNTIwMDQ2NSwicGF0aCI6Ii8zMjUxNzEzNy8zOTg0MTI2NTktMTJkZGE4OGEtMTllMy00NGE5LTliYjEtNjcyYjY4ZWE3MGExLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA4MDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYmExOTAxOGJlODNhNWI4ZDU3ODU0ODE5MTc2MjBkNDkxZjQ2MmRjZTA3OTViNWJlZmVjNTUwYjNhZjliMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MIEW1EZoRckB2Xy0e_YtHOLEIVlde4aMG6eeT6bkxiI
#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407469#case_4044803
