### ISSUE TITLE
Too much decimals in transactions details

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#698]
when making transactions and checking the transaction details it shows too many decimals (7 decimals).

![telegram-cloud-photo-size-4-5845935967645582439-y](https://github.com/user-attachments/assets/6ad35286-9802-486b-80ac-c34f630b48e3)

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
-  Transaction amount decimals have been reformatted.

![Image](https://github.com/user-attachments/assets/4561fedc-241e-4bfd-8b9c-a269f49bc05d)

![Image](https://github.com/user-attachments/assets/e52728ff-26cb-49d1-9181-08ae365b6733)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4046920
