### ISSUE TITLE
Failed to transfer message enhancement

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#700]
can we enhance the Failed to transfer message 
I was trying to send tfts from devnet wallet to mainnet wallet but i was not noticing 
can we clarify this in the error message "check if the wallets on the same network and try again"
![telegram-cloud-photo-size-4-5843636974731250570-y](https://github.com/user-attachments/assets/66564146-263c-42cc-84bd-124c3792f79c)

**Comment by ramezsaeed** [comment]
Try again.
this should succeed to transfer from any network to another using TF chain address.
