### ISSUE TITLE
Taping Dao or Farming buttons keep loading without reaching the target page 

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/threefold_connect#701]
### Description:

- When clicking on the Dao or Farming buttons, keep loading  without navigating to the intended page.

### Screenshot Of the Issue:
![1](https://github.com/user-attachments/assets/519c7e0d-28b4-4893-a85d-d5bfded00ce2)
![2](https://github.com/user-attachments/assets/15ad3857-002b-4b7f-98ef-12f5931f9d76)

### Environment:

 • OS Version: Android 14
 • App Version: 3.9.1
 • APK 30-10-2024

**Comment by AhmedHanafy725** [comment]
steps to reproduce?

**Comment by ramezsaeed** [comment]
can u test again on the lates version APK -31.10.20.25
@atefnazmy
