### ISSUE TITLE
Add security link for the user to check before starting the verification

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#724]
https://www.idenfy.com/security/

**Comment by khaledyoussef24** [comment]
Verified 
IOS 18
version 4.0.0
 
Idenfy is now updated KYC is added to Threefold connect app
link is added in the first step in verification after you verify your email and mobile number
![Image](https://github.com/user-attachments/assets/03e142f0-624f-44c9-9efc-2d15d7510467)




[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407477#case_4412645)
