### ISSUE TITLE
Allow setting/editing stellar payout address on farms

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#730]

**Comment by AlaaElattar** [comment]
### Work Completed:
- All done user can update stellar address either type it or choose one from its wallets.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Users can successfully update the Stellar payout address by typing or selecting it from their wallets


https://github.com/user-attachments/assets/44373adf-ca5f-49c9-8a8f-eb5ccec23379


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407474#case_4429815
