### ISSUE TITLE
Resend Verification SMS takes too long

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/threefold_connect#734]
while verifying the mobile number, it takes a lot of time to resend the sms or change the mobile number 
user have to wait for five minutes which is too long can we make it 2 minutes ?
![image](https://github.com/user-attachments/assets/8bc74ac5-797f-4ee1-a138-f1d3d7937de5)

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Sending verification SMS currently takes less than one minute.


https://github.com/user-attachments/assets/ac0534ff-a8f8-485c-9dea-7b1f3e94f8fe

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407477#case_4412644
