### ISSUE TITLE
Cannot create new farm using the Threefold Connect App

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/threefold_connect#747]
### Description:
- I'm unable to create a new farm using the Threefold Connect App and a popup window with an error message appears

### Steps to Reproduce:

- Open the Threefold Connect App.
- Click on the Farming button in main menu.
- Write your PIN code.
- Click on the "+" symbol on the top right.
- Write a name for your farm and select wallet then click on create.

### Screenshot Of the Issue:
![create_farm](https://github.com/user-attachments/assets/56c29a48-9e0d-4a64-bdfb-8e59570d79d1)

### Environment:

 • OS Version: Android 14
 • App Version: 4.0.0-181

**Comment by Elsonbastey** [comment]
> ### Description:
> * I'm unable to create a new farm using the Threefold Connect App and a popup window with an error message appears
> 
> ### Steps to Reproduce:
> * Open the Threefold Connect App.
> * Click on the Farming button in main menu.
> * Write your PIN code.
> * Click on the "+" symbol on the top right.
> * Write a name for your farm and select wallet then click on create.
> 
> ### Screenshot Of the Issue:
> ![create_farm](https://private-user-images.githubusercontent.com/32517137/385101198-56c29a48-9e0d-4a64-bdfb-8e59570d79d1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNzQyOTYsIm5iZiI6MTczMTM3Mzk5NiwicGF0aCI6Ii8zMjUxNzEzNy8zODUxMDExOTgtNTZjMjlhNDgtOWUwZC00YTY0LWJkZmItOGU1OTU3MGQ3OWQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDAxMTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiOTljZGMwZGYyY2ZhZDYzMzJlNjA3YzVjZWFmZjcxOTBmMjU5NmVlZDYxZWJhOTdmYTIwM2MwOWI2MzJmYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Csv8Nr7-puV6x1iXHIt-tgkdpo35PQVgJPvpgCIka_I)
> 
> ### Environment:
> • OS Version: Android 14 • App Version: 4.0.0-181

 
Hello @atefnazmy 
You're experiencing transcript error on the node. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID FAR19427
Please see the link below to our dedicated support line:
[Threefold Network DApps Support Ticket Requests.](https://thedappsupport.live)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by AhmedHanafy725** [comment]
### Work Completed

The connection to tfchain was closed before creating the farm.

**Comment by khaledyoussef24** [comment]
verified on IOS 18
Version 4.0.0

could create the farm 
on the mobile
![Image](https://github.com/user-attachments/assets/1a70efe2-8a68-4ab1-8a61-3837450aa21d)
![Image](https://github.com/user-attachments/assets/3ee9b1cc-adf4-4be7-9725-e6c529309e18)
![Image](https://github.com/user-attachments/assets/b006bc72-d120-46bd-8458-842d46fb6f06)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407474#case_4050852)
