### ISSUE TITLE
Create feature images and screens for App & play store

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/threefold_connect#750]

**Comment by ehab-hassan** [comment]
images sent to @AhmedHanafy725 at telegram

![feature_Iphon](https://github.com/user-attachments/assets/5ed0e8c1-ca59-4cd1-b695-d514f3998ade)
![home](https://github.com/user-attachments/assets/dd1106d4-177e-4ba8-af73-b13ce2f51236)
![wallet1](https://github.com/user-attachments/assets/10022c2e-4802-475e-bb51-dd66a2df0c0d)
![home_white](https://github.com/user-attachments/assets/bb311989-520e-45c4-b9b4-80c9e318ffa2)

**Comment by khaledyoussef24** [comment]
verified on app store
![Image](https://github.com/user-attachments/assets/e6c4a863-8fda-4488-b3e8-61cbb5cb9788)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=339409#case_4041641)
