### ISSUE TITLE
Support delete account

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#757]

**Comment by khaledyoussef24** [comment]
verified on version : 
IOS 18

![Image](https://github.com/user-attachments/assets/c07d2922-e3af-4b90-b61c-a82e22c26bc6)
![Image](https://github.com/user-attachments/assets/d2ac269b-41c8-442c-88a5-2269716bf218)
![Image](https://github.com/user-attachments/assets/4b339116-3a7c-486f-8c1f-050ccbc01828)
![Image](https://github.com/user-attachments/assets/35e60afd-4a90-4106-a735-42c0fc38a07f)
![Image](https://github.com/user-attachments/assets/035db7e9-ab8d-49a6-a8e5-b1e27bf31366)

[testcase 1](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407470#case_4421005)

[testcase 2](https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407478#case_4421006)

**Comment by ramezsaeed** [comment]
verified on Android 13, 14
