### ISSUE TITLE
Bridge Stellar <> TF Chain

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#764]
### Is your feature request related to a problem? Please describe

-

### Describe the solution you'd like

-

**Comment by zaelgohary** [comment]
Work completed:

Added Bridge screen with a swapping icon that enables users to swap TFTs between both chains.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The Bridge screen has been added with a swapping functionality, that allow users swapping between the chains


https://github.com/user-attachments/assets/4356ea32-2ce0-452f-ac37-dbe6be39f082


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4428107

**Comment by mik-tf** [comment]
Amazing work. Very useful. Any ETA on when it's available on TF Connect app? So I can align with manual docs: https://github.com/threefoldtech/info_grid/issues/711
Thanks!
