### ISSUE TITLE
Check if the wallet is activated on stellar network while validating stellar address before sending 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#767]

**Comment by AlaaElattar** [comment]
### Work Completed:
- When sending to existing wallet through stellar, will check first if stellar is activated on it or not.

**Comment by AlaaElattar** [comment]
### Work Completed:
- Supported checking on wallets that are not saved in my wallets.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The wallet activation status is correctly checked before proceeding with the transaction

![image](https://github.com/user-attachments/assets/78f29523-3745-40e7-8743-c33c78ef1cf4)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4434585
