### ISSUE TITLE
Exclude the stellar wallets that are not activated from the suggested list for sending

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/threefold_connect#768]
can be done by checking the wallet balance

**Comment by zaelgohary** [comment]
Work completed:

Filtered wallets to check if balance >= 0.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
-  Only activated Stellar wallets appears in the suggested list when users are selecting a recipient.


https://github.com/user-attachments/assets/c23a942d-e798-4273-8678-76debc77a695

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4048984
