### ISSUE TITLE
KYC verification error message should specify that TFChain must be funded and on Daily wallet

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/threefold_connect#771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While trying to verify my account I got a message that i should fund my wallet with minimum 100 TFT.
However i already has more than 200 in my daily wallet; but on stellar chain not TFchain.

so now the message should be fixed to specify the user need to fund the Daily wallet with 100 TFT and on TFchain.

### Relevant screenshots/screen records

![Screenshot from 2024-11-21 16-40-20](https://github.com/user-attachments/assets/76d0e363-d23b-42e8-b71c-e7d0626f784d)

### Relevant log output

```console
--
```

**Comment by mik-tf** [comment]
I second that. I had the same situation. Also this means we would need a clear process on how to fund the TFChain wallet. E.g. how to bridge from stellar to tfchain the 100 TFT.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- The error message clearly specifies that the TFChain account must be funded with at least 100 TFTs.

![image](https://github.com/user-attachments/assets/3965b241-cdf0-48a3-bd80-a3652982f1d8)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407477#case_4412645

**Comment by ramezsaeed** [comment]
regarding to this comment https://github.com/threefoldtech/threefold_connect/issues/771#issuecomment-2514903730
I think we may add a link or info how to do that transfer from stellar to tfchain using the bridge.

**Comment by zaelgohary** [comment]
> regarding to this comment [#771 (comment)](https://github.com/threefoldtech/threefold_connect/issues/771#issuecomment-2514903730) I think we may add a link or info how to do that transfer from stellar to tfchain using the bridge.

User may fund the wallet by either using bridge stellar => TF chain or by sending TFTs from TF chain wallet to another. Either way, I opened a feature request for it [here](https://github.com/threefoldtech/threefold_connect/issues/821) and we can close this one.
