### ISSUE TITLE
the back button in wallet doesn't update the amount after transfer 

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/threefold_connect#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

after do a successful transfer and hit the back button in wallet page;
can still see the wallet has the same old amount before the transfer.

### Steps To Reproduce

- open tf connect app
- go to wallet page
- select a wallet
- transfer TFT to anyone
- hit the back button in the top left corner
- will notice that the wallet still show the old TFT value

### after transfer done i should have this amount which is shown in the page inside the wallet:
![photo_2024-11-21_16-55-12](https://github.com/user-attachments/assets/808d6e35-625d-4f62-b239-12e76ad14f4f)

========================================================================
### but when hit the back button, it still show the old amount before the transfer done:
![photo_2024-11-21_16-55-09](https://github.com/user-attachments/assets/9b939d00-649a-4b14-b2c7-02534b43eb01)

### Relevant log output

```console
--
```

**Comment by AhmedHanafy725** [comment]
@ramezsaeed the wallet balances are refreshed every 10 seconds. so can you try again and wait for 10 seconds?

**Comment by ramezsaeed** [comment]
Yes, it is working within the 10 sec time frame.

**Comment by ramezsaeed** [comment]
will close this one
