### ISSUE TITLE
Apply KYC on the farmers

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/threefold_connect#778]
### Is your feature request related to a problem? Please describe

Farmers should go through KYC process if they want to interact with any farming features

### Describe the solution you'd like

Farmers should go through KYC process if they want to interact with any farming features

**Comment by AlaaElattar** [comment]
### Work in progress:
- Farmers can't create or edit wallet unless the farm's wallet is verified.

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Farmers cannot create a new farm if their KYC is not verified.

https://github.com/user-attachments/assets/93a41354-1d87-46aa-b23b-280b205ce27c

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4435696
