### ISSUE TITLE
Stellar & TFChain wallets have the same icon

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/user-attachments/assets/e22695cc-7e7d-4ab7-ac47-075ef6ca1b7d)

### Steps To Reproduce

1. Open app
2. Go to Wallets

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by ramezsaeed** [comment]
Also we can capitalize "WALLET"

**Comment by atefnazmy** [comment]
- Verified on Android 14,
- Threefold-Connect: 4.0.0-184
- APK:12-12-2024
- Stellar and TFChain wallets have their own icon.
-  The Letter "W" is currently written as Capitalized in "Wallet"

![Image](https://github.com/user-attachments/assets/e5a5762a-7fb8-4a18-a436-9b706b15a845)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/206114?expand_section=407473#case_4426895

**Comment by ramezsaeed** [comment]
> Also we can capitalize "WALLET"

We should also capitalize "wallet" as mentioned in the BAM.

**Comment by zaelgohary** [comment]
> > Also we can capitalize "WALLET"
> 
> We should also capitalize "wallet" as mentioned in the BAM.

We show the wallet name exactly as the user entered it. If the user enters the name capitalized, it'll be shown capitalized.

**Comment by atefnazmy** [comment]
https://github.com/threefoldtech/threefold_connect/issues/779#issuecomment-2544624347
