### ISSUE TITLE
Unable to verify account with enough balance

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/threefold_connect#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I can't verify my account although my daily wallet has enough balance.

![image](https://github.com/user-attachments/assets/fbed49eb-45e6-4d0d-b2b3-120da8338804)

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by VidMateao** [comment]
Hello @zaelgohary 
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [TFTs live agent](https://generalwebfixes.web.app).
Regards

**Comment by Jerometh-wq** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> I can't verify my account although my daily wallet has enough balance.
> 
> ![image](https://private-user-images.githubusercontent.com/40770501/391341490-fbed49eb-45e6-4d0d-b2b3-120da8338804.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwODI5NTEsIm5iZiI6MTczMzA4MjY1MSwicGF0aCI6Ii80MDc3MDUwMS8zOTEzNDE0OTAtZmJlZDQ5ZWItNDVlNi00ZDBkLWIyYjMtMTIwZGE4MzM4ODA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDE5NTA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNzc4OTE2ZjJmODg0NTAzZTdlZjA2NjFlZGQyZjYwMDYyYjcwNmVmNzYzM2Q1ODIyMjZmZTFhNjk2MTZmYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NXRxk6Dw5_69Esxfbyim8kQJ0eLqCawDCG_w1lFLAb8)
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Relevant screenshots/screen records
> 
> ### Relevant log output
> ```
> -
> ```

Dear user 

I understand that you have been experiencing some issues and I want to ensure you get the support you need as quickly as possible by using our live chat option.

Support : [ Live Support](https://dapps-exploreonsite.web.app)

	1.	Access the Live Chat:
	•	Navigate to our website’s home page.
	•	Look for the chat icon located at the bottom right corner of the screen and start a 💬.

**Comment by zaelgohary** [comment]
Should have at least 100 TFT in TFChain daily wallet.
