### ISSUE TITLE
Error message "failed to send" when trying to contact support through the threefold.io website.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/threefold_connect#812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Some farmers report receiving a "failed to send" error when attempting to contact support via the threefold.io website.

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/670435a8-f54d-4fa5-a48f-21301ed1b324)

### Relevant log output

```console
Every attempt returned a message "failed to send,
retry?"
```

**Comment by TullysInc** [comment]
Tested this scenario multiple times and the issue appears to have resolved.
